import { chromium } from 'playwright';
import { mkdir, writeFile } from 'node:fs/promises';
const base=process.env.FLOW_BASE_URL||'http://127.0.0.1:4173';
await mkdir('university-audit',{recursive:true});
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:412,height:915},locale:'ko-KR',isMobile:true,hasTouch:true,colorScheme:'dark'});
const page=await context.newPage();
const consoleErrors=[],pageErrors=[];
page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});page.on('pageerror',e=>pageErrors.push(String(e)));
await page.addInitScript(()=>{
  const d=(new Date().getDay()+6)%7;
  const t=(name,start,end,place)=>({name,professor:'테스트',times:[{day:d,start,end,startMinutes:Number(start.slice(0,2))*60+Number(start.slice(3)),endMinutes:Number(end.slice(0,2))*60+Number(end.slice(3)),place}]});
  localStorage.setItem('flow-university-profile-v1',JSON.stringify({id:'knu',name:'경북대학교',address:'대구광역시 북구 대학로 80',region:'대구'}));
  localStorage.setItem('flow-university-timetable-v1',JSON.stringify({year:2026,semester:'2학기',subjects:[t('자료구조','08:00','09:30','IT대학1호관'),t('운영체제','11:00','12:15','공대9호관'),t('컴퓨터네트워크','14:00','15:30','IT융합산업빌딩')]}));
  localStorage.removeItem('flow-university-dashboard-v1');
});
await page.goto(`${base}/university/`,{waitUntil:'domcontentloaded'});
await page.locator('#widgetDashboard').waitFor({timeout:10000});
await page.locator('#appView').waitFor({state:'visible'});
const initial=await page.evaluate(()=>({mode:[...document.querySelectorAll('.brand-mode')].map(x=>x.textContent.trim()),visible:[...document.querySelectorAll('#widgetDashboard [data-widget-id]')].filter(x=>!x.classList.contains('widget-hidden')).map(x=>x.dataset.widgetId),width:document.querySelector('#widgetDashboard').getBoundingClientRect().width,bodyWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth}));
if(!initial.mode.length||initial.mode.some(x=>x!=='University'))throw new Error(`Mode label missing: ${JSON.stringify(initial)}`);
if(initial.visible.length<6)throw new Error(`Too few default widgets: ${JSON.stringify(initial)}`);
if(initial.scrollWidth>initial.bodyWidth+3)throw new Error(`Dashboard causes horizontal scroll: ${JSON.stringify(initial)}`);
await page.locator('#dashboardEditBtn').click();
if(!await page.locator('#todayView.dashboard-editing').count())throw new Error('Edit mode did not start.');
const beforeSize=await page.locator('[data-widget-id="campus"]').getAttribute('data-size');
await page.locator('[data-widget-id="campus"] .widget-size').click();
const afterSize=await page.locator('[data-widget-id="campus"]').getAttribute('data-size');
if(beforeSize===afterSize)throw new Error('Widget size did not change.');
await page.locator('[data-widget-id="gap"] .widget-hide').click();
if(!await page.locator('[data-widget-id="gap"].widget-hidden').count())throw new Error('Widget hide failed.');
await page.locator('#widgetAddBtn').click();
await page.locator('#widgetPicker').waitFor({state:'visible'});
await page.locator('[data-picker-id="gap"]').click();
await page.locator('[data-widget-picker-close]').click();
if(await page.locator('[data-widget-id="gap"].widget-hidden').count())throw new Error('Widget restore failed.');
const orderBefore=await page.evaluate(()=>[...document.querySelectorAll('#widgetDashboard [data-widget-id]:not(.widget-hidden)')].map(x=>x.dataset.widgetId));
const handle=page.locator('[data-widget-id="today"] .widget-grab'),target=page.locator('[data-widget-id="next"]');
const hb=await handle.boundingBox(),tb=await target.boundingBox();
if(hb&&tb){await page.mouse.move(hb.x+hb.width/2,hb.y+hb.height/2);await page.mouse.down();await page.mouse.move(tb.x+6,tb.y+6,{steps:8});await page.mouse.up();}
const orderAfter=await page.evaluate(()=>[...document.querySelectorAll('#widgetDashboard [data-widget-id]:not(.widget-hidden)')].map(x=>x.dataset.widgetId));
if(orderBefore.join('|')===orderAfter.join('|'))throw new Error(`Widget drag did not reorder: ${JSON.stringify({orderBefore,orderAfter})}`);
await page.locator('#widgetDoneBtn').click();
const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('flow-university-dashboard-v1')||'null'));
if(!Array.isArray(saved)||saved.length<8)throw new Error('Dashboard layout was not persisted.');
if(saved.find(x=>x.id==='campus')?.size!==afterSize)throw new Error(`Widget size was not persisted: ${JSON.stringify(saved)}`);
await page.reload({waitUntil:'domcontentloaded'});await page.locator('#widgetDashboard').waitFor();
const reloaded=await page.evaluate(()=>({size:document.querySelector('[data-widget-id="campus"]')?.dataset.size,order:[...document.querySelectorAll('#widgetDashboard [data-widget-id]')].map(x=>x.dataset.widgetId)}));
if(reloaded.size!==afterSize)throw new Error(`Reload lost widget size: ${JSON.stringify(reloaded)}`);
await page.locator('#dashboardEditBtn').click();await page.locator('#widgetDoneBtn').click();
const next=page.locator('[data-widget-id="next"]'),box=await next.boundingBox();if(box){await next.dispatchEvent('pointerdown',{button:0,clientX:box.x+10,clientY:box.y+10,pointerId:77,pointerType:'touch'});await page.waitForTimeout(620);await next.dispatchEvent('pointerup',{button:0,clientX:box.x+10,clientY:box.y+10,pointerId:77,pointerType:'touch'});}
if(!await page.locator('#todayView.dashboard-editing').count())throw new Error('Long press did not enter edit mode.');
await page.locator('#widgetDoneBtn').click();
const idleMutations=await page.evaluate(async()=>{let count=0;const root=document.querySelector('#todayView');const o=new MutationObserver(m=>count+=m.length);o.observe(root,{subtree:true,childList:true,characterData:true,attributes:true});await new Promise(r=>setTimeout(r,1200));o.disconnect();return count});
if(idleMutations!==0)throw new Error(`Dashboard mutates while idle: ${idleMutations}`);
await page.screenshot({path:'university-audit/mobile-dashboard.png',fullPage:true});
await page.setViewportSize({width:1440,height:900});await page.waitForTimeout(150);
const desktopOverflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);
if(desktopOverflow>3)throw new Error(`Desktop dashboard horizontal overflow: ${desktopOverflow}`);
await page.screenshot({path:'university-audit/desktop-dashboard.png',fullPage:true});
const report={initial,beforeSize,afterSize,orderBefore,orderAfter,reloaded,idleMutations,consoleErrors,pageErrors};
await writeFile('university-audit/dashboard-report.json',JSON.stringify(report,null,2));
console.log(JSON.stringify(report,null,2));
if(consoleErrors.length||pageErrors.length)throw new Error(`Browser errors: ${JSON.stringify({consoleErrors,pageErrors})}`);
await browser.close();