const LAYOUT_KEY='flow-university-dashboard-v1';
const TIMETABLE_KEY='flow-university-timetable-v1';
const PROFILE_KEY='flow-university-profile-v1';
const LONG_PRESS_MS=520;
const WIDGETS={
  next:{label:'다음 수업',hint:'다음 수업 시간·강의실',defaultSize:'wide',sizes:['small','wide','large'],visible:true},
  today:{label:'오늘 수업',hint:'오늘 등록된 수업 개수',defaultSize:'small',sizes:['small','wide'],visible:true},
  semester:{label:'이번 학기',hint:'학기와 시간표 상태',defaultSize:'small',sizes:['small','wide'],visible:true},
  schedule:{label:'오늘 일정',hint:'오늘 수업을 목록으로 보기',defaultSize:'large',sizes:['wide','large'],visible:true},
  campus:{label:'다음 강의실',hint:'다음 강의실과 도보 이동',defaultSize:'small',sizes:['small','wide'],visible:true},
  gap:{label:'빈 시간',hint:'다음 20분 이상 공강',defaultSize:'small',sizes:['small','wide'],visible:true},
  clock:{label:'현재 시각',hint:'현재 시간과 날짜',defaultSize:'small',sizes:['small','wide'],visible:false},
  progress:{label:'수업 진행률',hint:'현재 수업 진행·남은 시간',defaultSize:'wide',sizes:['small','wide','large'],visible:false},
  remaining:{label:'남은 수업',hint:'오늘 남은 수업 개수',defaultSize:'small',sizes:['small','wide'],visible:false},
  tomorrow:{label:'내일 첫 수업',hint:'내일 첫 수업 시간·장소',defaultSize:'wide',sizes:['small','wide','large'],visible:false},
  credits:{label:'이번 학기 학점',hint:'가져온 과목의 실제 학점 합계',defaultSize:'small',sizes:['small','wide'],visible:false},
  shortcuts:{label:'바로가기',hint:'시간표·캠퍼스·학교·가져오기',defaultSize:'wide',sizes:['small','wide','large'],visible:false},
  week:{label:'이번 주',hint:'이번 주 시간 블록 요약',defaultSize:'small',sizes:['small','wide','large'],visible:false},
  dayflow:{label:'오늘 흐름',hint:'현재부터 이어지는 수업 타임라인',defaultSize:'wide',sizes:['small','wide','large'],visible:false},
  weekload:{label:'주간 밀도',hint:'요일별 수업시간과 공강 분포',defaultSize:'large',sizes:['small','wide','large'],visible:false},
  backup:{label:'내 데이터',hint:'로컬 저장·백업 관리',defaultSize:'small',sizes:['small','wide'],visible:false},
};
const DEFAULT_ORDER=Object.keys(WIDGETS);
let editing=false,dragging=null,longPressTimer=null,longPressStart=null;
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
function read(key,fallback=null){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function write(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function todayIndex(){return(new Date().getDay()+6)%7}
function minuteText(n){if(!Number.isFinite(n))return'—';const h=Math.floor(n/60)%24,m=n%60;return`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`}
function timetable(){return read(TIMETABLE_KEY,null)}
function entries(){const tt=timetable();if(!tt?.subjects)return[];return tt.subjects.flatMap(subject=>(subject.times||[]).map(time=>({...time,subject,place:String(time.place||subject.place||'').trim()}))).filter(x=>Number.isFinite(x.day)&&Number.isFinite(x.startMinutes)&&Number.isFinite(x.endMinutes)).sort((a,b)=>a.day-b.day||a.startMinutes-b.startMinutes)}
function dayEntries(day){return entries().filter(x=>x.day===day)}
function injectStyles(){for(const href of ['/university/dashboard.css','/university/dashboard-variants.css']){if(document.querySelector(`link[href="${href}"]`))continue;const link=document.createElement('link');link.rel='stylesheet';link.href=href;document.head.append(link)}}
function injectModeLabels(){$$('.brand').forEach(brand=>{if($('.brand-mode',brand))return;const mode=document.createElement('span');mode.className='brand-mode';mode.textContent='University';brand.append(mode)})}
function normalizedLayout(){const saved=read(LAYOUT_KEY,null);const byId=new Map(Array.isArray(saved)?saved.map(x=>[x.id,x]):[]);return DEFAULT_ORDER.map((id,index)=>{const m=WIDGETS[id],s=byId.get(id)||{};return{id,size:m.sizes.includes(s.size)?s.size:m.defaultSize,visible:typeof s.visible==='boolean'?s.visible:m.visible,order:Number.isFinite(s.order)?s.order:index}}).sort((a,b)=>a.order-b.order)}
function saveLayout(){const grid=$('#widgetDashboard');if(!grid)return;const state=$$('[data-widget-id]',grid).map((el,order)=>({id:el.dataset.widgetId,size:el.dataset.size||WIDGETS[el.dataset.widgetId]?.defaultSize||'small',visible:!el.classList.contains('widget-hidden'),order}));write(LAYOUT_KEY,state)}
function makeControls(el){if($('.widget-controls',el))return;const controls=document.createElement('div');controls.className='widget-controls';controls.innerHTML='<button class="widget-grab" type="button" aria-label="위젯 이동">⋮⋮</button><button class="widget-size" type="button" aria-label="위젯 크기 변경">크기</button><button class="widget-hide" type="button" aria-label="위젯 숨기기">×</button>';el.append(controls);$('.widget-size',controls).addEventListener('click',e=>{e.stopPropagation();cycleSize(el)});$('.widget-hide',controls).addEventListener('click',e=>{e.stopPropagation();el.classList.add('widget-hidden');saveLayout();refreshPicker()});const grab=$('.widget-grab',controls);grab.addEventListener('pointerdown',startDrag)}
function prepare(el,id){el.classList.add('dashboard-widget');el.dataset.widgetId=id;el.dataset.widgetLabel=WIDGETS[id].label;makeControls(el);bindLongPress(el);return el}
function customWidget(id,label,body,extra=''){const el=document.createElement('article');el.className=`summary-card dashboard-widget utility-widget ${extra}`.trim();el.innerHTML=`<span>${esc(label)}</span>${body}`;return prepare(el,id)}
function addDetail(el,html){const node=document.createElement('div');node.className='widget-variant-detail';node.innerHTML=html;const controls=$('.widget-controls',el);el.insertBefore(node,controls||null);return node}
function miniRows(list,limit=3){return list.slice(0,limit).map(x=>`<div class="widget-mini-row"><time>${esc(x.start||minuteText(x.startMinutes))}</time><span>${esc(x.subject?.name||'일정')}</span><small>${esc(x.place||'')}</small></div>`).join('')}
function dayBars(all){const days=['월','화','수','목','금','토','일'],minutes=days.map((_,day)=>all.filter(x=>x.day===day).reduce((sum,x)=>sum+Math.max(0,x.endMinutes-x.startMinutes),0)),max=Math.max(1,...minutes);return `<div class="widget-day-bars">${days.map((d,i)=>`<div title="${d} ${minutes[i]}분"><i style="--bar:${Math.round(minutes[i]/max*100)}%"></i><span>${d}</span></div>`).join('')}</div>`}
function buildDashboard(){
  const view=$('#todayView');if(!view||$('#widgetDashboard'))return;injectModeLabels();const summary=$('.summary-grid',view),content=$('.content-grid',view);if(!summary||!content)return;
  const summaryCards=[...summary.children],next=summaryCards[0],today=summaryCards[1],semester=summaryCards[2],schedule=$('.today-list-panel',content),importPanel=$('#emptyImportPanel');prepare(next,'next');prepare(today,'today');prepare(semester,'semester');prepare(schedule,'schedule');
  addDetail(next,'<div id="widgetNextDetail" class="widget-detail-wide"></div><div id="widgetNextLarge" class="widget-detail-large"></div>');
  addDetail(today,'<div id="widgetTodayDetail" class="widget-detail-wide"></div>');
  const campus=customWidget('campus','다음 강의실','<strong id="widgetCampusTitle">—</strong><p id="widgetCampusMeta">캠퍼스 이동을 확인합니다.</p><button class="widget-link" id="widgetCampusBtn" type="button">캠퍼스 보기</button>');
  const gap=customWidget('gap','빈 시간','<strong id="widgetGapTitle">—</strong><p id="widgetGapMeta">오늘 수업 사이</p>');
  const clock=customWidget('clock','현재 시각','<strong class="widget-clock-time" id="widgetClockTitle">--:--</strong><p id="widgetClockMeta">오늘 날짜</p>','clock-widget');
  const progress=customWidget('progress','수업 진행률','<strong id="widgetProgressTitle">수업 확인 중</strong><p id="widgetProgressMeta">시간표 기준</p><div class="widget-progress-track" aria-hidden="true"><i id="widgetProgressBar"></i></div><div id="widgetProgressDetail" class="widget-detail-large"></div>','progress-widget');
  const remaining=customWidget('remaining','남은 수업','<strong id="widgetRemainingTitle">—</strong><p id="widgetRemainingMeta">오늘 시간표 기준</p><div id="widgetRemainingDetail" class="widget-detail-wide"></div>');
  const tomorrow=customWidget('tomorrow','내일 첫 수업','<strong id="widgetTomorrowTitle">—</strong><p id="widgetTomorrowMeta">내일 시간표 기준</p><div id="widgetTomorrowDetail" class="widget-detail-large"></div>');
  const credits=customWidget('credits','이번 학기 학점','<strong id="widgetCreditsTitle">—</strong><p id="widgetCreditsMeta">가져온 과목 기준</p>');
  const shortcuts=customWidget('shortcuts','바로가기','<div class="widget-shortcut-grid"><button type="button" data-widget-shortcut="timetable">시간표</button><button type="button" data-widget-shortcut="campus">캠퍼스</button><button type="button" data-widget-shortcut="school">학교</button><button type="button" data-widget-shortcut="import">가져오기</button></div>','shortcuts-widget');
  const week=customWidget('week','이번 주','<strong id="widgetWeekTitle">—</strong><p id="widgetWeekMeta">주간 일정</p><div id="widgetWeekBars" class="widget-detail-wide"></div><button class="widget-link" id="widgetWeekBtn" type="button">시간표 보기</button>');
  const dayflow=customWidget('dayflow','오늘 흐름','<strong id="widgetDayflowTitle">—</strong><p id="widgetDayflowMeta">현재부터 이어지는 일정</p><div class="widget-dayflow-list" id="widgetDayflowList"></div>','dayflow-widget');
  const weekload=customWidget('weekload','주간 밀도','<strong id="widgetWeekloadTitle">—</strong><p id="widgetWeekloadMeta">요일별 수업시간</p><div id="widgetWeekloadBars"></div><div id="widgetWeekloadDetail" class="widget-detail-large"></div>','weekload-widget');
  const backup=customWidget('backup','내 데이터','<strong id="widgetBackupTitle">이 기기에 저장</strong><p id="widgetBackupMeta">JSON 백업 가능</p><button class="widget-link" id="widgetBackupBtn" type="button">백업 관리</button>');
  const grid=document.createElement('section');grid.id='widgetDashboard';grid.className='widget-dashboard';[next,today,semester,schedule,campus,gap,clock,progress,remaining,tomorrow,credits,shortcuts,week,dayflow,weekload,backup].forEach(x=>grid.append(x));summary.replaceWith(grid);content.classList.add('dashboard-import-wrap');if(schedule.parentElement===content)grid.append(schedule);if(importPanel&&importPanel.parentElement!==content)content.append(importPanel);
  const header=$('.hero-header',view),importBtn=$('#importTopBtn');if(header&&importBtn){const actions=document.createElement('div');actions.className='dashboard-top-actions';const edit=document.createElement('button');edit.id='dashboardEditBtn';edit.className='soft-button dashboard-edit-button';edit.type='button';edit.textContent='위젯 편집';actions.append(edit,importBtn);header.append(actions);edit.addEventListener('click',()=>setEditing(!editing))}
  const editor=document.createElement('div');editor.id='widgetEditorBar';editor.className='widget-editor-bar hidden';editor.innerHTML='<strong>대시보드 편집</strong><span>카드를 끌어 옮기고 오른쪽 아래를 당겨 크기를 조절할 수 있어요.</span><div><button class="soft-button" id="widgetAddBtn" type="button">+ 위젯</button><button class="soft-button" id="widgetResetBtn" type="button">초기화</button><button class="primary-button" id="widgetDoneBtn" type="button">완료</button></div>';grid.before(editor);
  $('#widgetAddBtn')?.addEventListener('click',openPicker);$('#widgetResetBtn')?.addEventListener('click',resetLayout);$('#widgetDoneBtn')?.addEventListener('click',()=>setEditing(false));$('#widgetCampusBtn')?.addEventListener('click',()=>openView('campus'));$('#widgetWeekBtn')?.addEventListener('click',()=>openView('timetable'));$('#widgetBackupBtn')?.addEventListener('click',()=>$('#changeUniversityBtn')?.click());
  $$('.widget-shortcut-grid [data-widget-shortcut]',shortcuts).forEach(btn=>btn.addEventListener('click',()=>{const target=btn.dataset.widgetShortcut;if(target==='import'){($('#importTopBtn')||$('#importTimetableBtn')||$('#importSidebarBtn'))?.click();return}openView(target)}));
  ensurePicker();applyLayout();refreshMetrics()
}
function openView(view){const b=document.querySelector(`[data-view="${view}"]`);if(b){b.click();return}if(view==='campus')location.href='/university/campus';if(view==='timetable')location.href='/university/timetable';if(view==='school')location.href='/university/school'}
function applyLayout(){const grid=$('#widgetDashboard');if(!grid)return;for(const item of normalizedLayout()){const el=grid.querySelector(`[data-widget-id="${item.id}"]`);if(!el)continue;el.dataset.size=item.size;el.classList.toggle('widget-hidden',!item.visible);grid.append(el)}refreshPicker()}
function setEditing(on){editing=Boolean(on);const view=$('#todayView');if(!view)return;view.classList.toggle('dashboard-editing',editing);$('#widgetEditorBar')?.classList.toggle('hidden',!editing);const btn=$('#dashboardEditBtn');if(btn)btn.textContent=editing?'편집 중':'위젯 편집';if(!editing){dragging=null;document.body.classList.remove('widget-drag-active');saveLayout()}}
function cycleSize(el){const meta=WIDGETS[el.dataset.widgetId],sizes=meta?.sizes||['small','wide','large'];const current=sizes.indexOf(el.dataset.size),next=sizes[(current+1)%sizes.length];el.dataset.size=next;saveLayout()}
function bindLongPress(el){el.addEventListener('pointerdown',e=>{if(editing||e.button!==0||e.target.closest('.widget-controls,button,a,textarea,input,select'))return;longPressStart={x:e.clientX,y:e.clientY};clearTimeout(longPressTimer);longPressTimer=setTimeout(()=>{setEditing(true);try{navigator.vibrate?.(18)}catch{}},LONG_PRESS_MS)});el.addEventListener('pointermove',e=>{if(!longPressStart)return;if(Math.hypot(e.clientX-longPressStart.x,e.clientY-longPressStart.y)>10){clearTimeout(longPressTimer);longPressStart=null}});['pointerup','pointercancel','pointerleave'].forEach(type=>el.addEventListener(type,()=>{clearTimeout(longPressTimer);longPressStart=null}))}
function startDrag(e){if(!editing)return;e.preventDefault();const widget=e.currentTarget.closest('[data-widget-id]');if(!widget)return;dragging=widget;widget.classList.add('widget-dragging');document.body.classList.add('widget-drag-active');e.currentTarget.setPointerCapture?.(e.pointerId);document.addEventListener('pointermove',dragMove);document.addEventListener('pointerup',endDrag,{once:true});document.addEventListener('pointercancel',endDrag,{once:true})}
function dragMove(e){if(!dragging)return;const target=document.elementFromPoint(e.clientX,e.clientY)?.closest?.('[data-widget-id]');if(!target||target===dragging||target.parentElement!==dragging.parentElement||target.classList.contains('widget-hidden'))return;const r=target.getBoundingClientRect(),before=e.clientY<r.top+r.height/2||(Math.abs(e.clientY-(r.top+r.height/2))<r.height*.22&&e.clientX<r.left+r.width/2);target.parentElement.insertBefore(dragging,before?target:target.nextSibling)}
function endDrag(){if(dragging)dragging.classList.remove('widget-dragging');dragging=null;document.body.classList.remove('widget-drag-active');document.removeEventListener('pointermove',dragMove);saveLayout()}
function ensurePicker(){if($('#widgetPicker'))return;const d=document.createElement('dialog');d.id='widgetPicker';d.innerHTML='<div class="dialog-sheet widget-picker-sheet"><button class="dialog-close" data-widget-picker-close type="button" aria-label="닫기">×</button><span class="kicker">WIDGETS</span><h2>위젯 추가</h2><p>필요한 정보만 오늘 화면에 올려둘 수 있습니다.</p><div class="widget-picker-list" id="widgetPickerList"></div></div>';document.body.append(d);$('[data-widget-picker-close]',d).addEventListener('click',()=>d.close())}
function openPicker(){ensurePicker();refreshPicker();const d=$('#widgetPicker');if(d&&!d.open)d.showModal()}
function refreshPicker(){const box=$('#widgetPickerList');if(!box)return;const grid=$('#widgetDashboard');box.innerHTML=DEFAULT_ORDER.map(id=>{const el=grid?.querySelector(`[data-widget-id="${id}"]`),shown=el&&!el.classList.contains('widget-hidden'),meta=WIDGETS[id];return`<button class="widget-picker-item${shown?' is-added':''}" type="button" data-picker-id="${id}"><span><strong>${esc(meta.label)}</strong><small>${shown?'오늘 화면에 표시 중':esc(meta.hint||'탭해서 추가')}</small></span><b>${shown?'✓':'+'}</b></button>`}).join('');$$('[data-picker-id]',box).forEach(btn=>btn.addEventListener('click',()=>{const el=grid?.querySelector(`[data-widget-id="${btn.dataset.pickerId}"]`);if(!el)return;el.classList.toggle('widget-hidden');saveLayout();refreshPicker()}))}
function resetLayout(){localStorage.removeItem(LAYOUT_KEY);applyLayout();setEditing(true)}
function refreshMetrics(){
  const tt=timetable(),all=entries(),today=todayIndex(),day=all.filter(x=>x.day===today),now=new Date(),mins=now.getHours()*60+now.getMinutes(),current=day.find(x=>x.startMinutes<=mins&&x.endMinutes>mins),future=day.filter(x=>x.startMinutes>mins),remaining=day.filter(x=>x.endMinutes>mins),upcoming=day.find(x=>x.startMinutes>mins&&x.place);
  const campusTitle=$('#widgetCampusTitle'),campusMeta=$('#widgetCampusMeta');if(campusTitle){campusTitle.textContent=upcoming?.place||'오늘 이동 없음';campusMeta.textContent=upcoming?[upcoming.start,upcoming.subject?.name].filter(Boolean).join(' · '):'남은 강의실 이동이 없습니다.'}
  let gap=null;for(let i=0;i<day.length-1;i++){const a=day[i],b=day[i+1],duration=b.startMinutes-a.endMinutes;if(duration>=20&&a.endMinutes>=mins-5){gap={start:a.endMinutes,end:b.startMinutes,duration};break}}const gapTitle=$('#widgetGapTitle'),gapMeta=$('#widgetGapMeta');if(gapTitle){gapTitle.textContent=gap?`${gap.duration}분`:(tt?'여유 없음':'—');gapMeta.textContent=gap?`${minuteText(gap.start)}–${minuteText(gap.end)}`:(tt?'20분 이상 공강 없음':'시간표를 가져오세요')}
  const clockTitle=$('#widgetClockTitle'),clockMeta=$('#widgetClockMeta');if(clockTitle){clockTitle.textContent=new Intl.DateTimeFormat('ko-KR',{hour:'2-digit',minute:'2-digit',hour12:false}).format(now);clockMeta.textContent=new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric',weekday:'short'}).format(now)}
  const progressTitle=$('#widgetProgressTitle'),progressMeta=$('#widgetProgressMeta'),progressBar=$('#widgetProgressBar');if(progressTitle){let pct=0;if(current){const duration=Math.max(1,current.endMinutes-current.startMinutes),elapsed=Math.max(0,mins-current.startMinutes),left=Math.max(0,current.endMinutes-mins);pct=Math.max(0,Math.min(100,elapsed/duration*100));progressTitle.textContent=current.subject?.name||'수업 중';progressMeta.textContent=`${current.end||minuteText(current.endMinutes)} 종료 · ${left}분 남음`}else if(future[0]){progressTitle.textContent=`다음 ${future[0].start||minuteText(future[0].startMinutes)}`;progressMeta.textContent=[future[0].subject?.name,future[0].place].filter(Boolean).join(' · ')}else{progressTitle.textContent=tt?'오늘 수업 끝':'—';progressMeta.textContent=tt?'남은 수업이 없습니다.':'시간표를 가져오세요'}if(progressBar)progressBar.style.width=`${pct}%`}
  const nextDetail=$('#widgetNextDetail'),nextLarge=$('#widgetNextLarge');if(nextDetail)nextDetail.innerHTML=future[0]?`<span>시작</span><strong>${esc(future[0].start||minuteText(future[0].startMinutes))}</strong><small>${esc(future[0].place||future[0].subject?.professor||'')}</small>`:(current?`<span>진행 중</span><strong>${Math.max(0,current.endMinutes-mins)}분 남음</strong>`:'');if(nextLarge)nextLarge.innerHTML=miniRows((current?[current]:[]).concat(future),3);
  const todayDetail=$('#widgetTodayDetail');if(todayDetail)todayDetail.innerHTML=miniRows(day,2);
  const progressDetail=$('#widgetProgressDetail');if(progressDetail)progressDetail.innerHTML=miniRows(future,2);
  const remainingTitle=$('#widgetRemainingTitle'),remainingMeta=$('#widgetRemainingMeta');if(remainingTitle){remainingTitle.textContent=tt?`${remaining.length}개`:'—';remainingMeta.textContent=remaining.length?(current?'현재 수업 포함':`다음 ${remaining[0].start||minuteText(remaining[0].startMinutes)}`):(tt?'오늘 일정 종료':'시간표 미등록')}
  const remainingDetail=$('#widgetRemainingDetail');if(remainingDetail)remainingDetail.innerHTML=miniRows(remaining,2);
  const tomorrowDay=(today+1)%7,tomorrowList=all.filter(x=>x.day===tomorrowDay),tomorrowFirst=tomorrowList[0],tomorrowTitle=$('#widgetTomorrowTitle'),tomorrowMeta=$('#widgetTomorrowMeta');if(tomorrowTitle){tomorrowTitle.textContent=tomorrowFirst?(tomorrowFirst.subject?.name||'일정'):(tt?'수업 없음':'—');tomorrowMeta.textContent=tomorrowFirst?[tomorrowFirst.start||minuteText(tomorrowFirst.startMinutes),tomorrowFirst.place].filter(Boolean).join(' · '):(tt?'내일 등록된 일정 없음':'시간표 미등록')}
  const tomorrowDetail=$('#widgetTomorrowDetail');if(tomorrowDetail)tomorrowDetail.innerHTML=miniRows(tomorrowList.slice(1),2);
  const nonCustom=(tt?.subjects||[]).filter(x=>!x.custom),creditValues=nonCustom.map(x=>Number(x.credit)).filter(x=>Number.isFinite(x)&&x>0),creditTotal=creditValues.reduce((a,b)=>a+b,0),creditsTitle=$('#widgetCreditsTitle'),creditsMeta=$('#widgetCreditsMeta');if(creditsTitle){creditsTitle.textContent=creditTotal>0?`${creditTotal.toLocaleString('ko-KR',{maximumFractionDigits:1})}학점`:'—';creditsMeta.textContent=creditTotal>0?`${nonCustom.length}개 과목 기준`:(tt?`${nonCustom.length}개 과목 · 학점 정보 없음`:'시간표 미등록')}
  const weekTitle=$('#widgetWeekTitle'),weekMeta=$('#widgetWeekMeta'),weekBars=$('#widgetWeekBars');if(weekTitle){const subjects=tt?.subjects?.length||0;weekTitle.textContent=tt?`${all.length}개 일정`:'—';weekMeta.textContent=tt?`${subjects}개 과목 · ${tt.year||''} ${tt.semester||''}`.trim():'시간표 미등록';if(weekBars)weekBars.innerHTML=tt?dayBars(all):''}
  const timeline=(current?[current]:future).concat(current?future:[]).slice(0,3),dayflowTitle=$('#widgetDayflowTitle'),dayflowMeta=$('#widgetDayflowMeta'),dayflowList=$('#widgetDayflowList');if(dayflowTitle){if(current){dayflowTitle.textContent=current.subject?.name||'수업 중';dayflowMeta.textContent=`${Math.max(0,current.endMinutes-mins)}분 후 종료`}else if(future[0]){const wait=Math.max(0,future[0].startMinutes-mins);dayflowTitle.textContent=future[0].subject?.name||'다음 일정';dayflowMeta.textContent=wait?`${wait}분 후 · ${future[0].start||minuteText(future[0].startMinutes)}`:`${future[0].start||minuteText(future[0].startMinutes)} 시작`}else{dayflowTitle.textContent=tt?'오늘 일정 완료':'—';dayflowMeta.textContent=tt?'남은 수업이 없습니다.':'시간표 미등록'}if(dayflowList)dayflowList.innerHTML=miniRows(timeline,3)}
  const dayMinutes=Array.from({length:7},(_,d)=>all.filter(x=>x.day===d).reduce((sum,x)=>sum+Math.max(0,x.endMinutes-x.startMinutes),0)),totalMinutes=dayMinutes.reduce((a,b)=>a+b,0),maxMinutes=Math.max(0,...dayMinutes),busy=maxMinutes?dayMinutes.indexOf(maxMinutes):-1,free=dayMinutes.slice(0,5).map((v,i)=>v===0?i:-1).filter(i=>i>=0),dayNames=['월','화','수','목','금','토','일'],weekloadTitle=$('#widgetWeekloadTitle'),weekloadMeta=$('#widgetWeekloadMeta'),weekloadBars=$('#widgetWeekloadBars'),weekloadDetail=$('#widgetWeekloadDetail');if(weekloadTitle){weekloadTitle.textContent=tt?`${(totalMinutes/60).toLocaleString('ko-KR',{maximumFractionDigits:1})}시간`:'—';weekloadMeta.textContent=tt?(busy>=0?`${dayNames[busy]}요일이 가장 바쁨`:'수업 없음'):'시간표 미등록';if(weekloadBars)weekloadBars.innerHTML=tt?dayBars(all):'';if(weekloadDetail)weekloadDetail.innerHTML=tt?`<span>평일 공강</span><strong>${free.length?free.map(i=>dayNames[i]).join(' · '):'없음'}</strong><small>${all.length}개 시간 블록</small>`:''}
  const profile=read(PROFILE_KEY,null),backupMeta=$('#widgetBackupMeta');if(backupMeta)backupMeta.textContent=profile?`${profile.name||'대학교'} · 백업 저장 가능`:'대학을 먼저 선택하세요'
}
function bindRefresh(){window.addEventListener('flow:timetable-changed',refreshMetrics);window.addEventListener('storage',e=>{if([TIMETABLE_KEY,PROFILE_KEY,LAYOUT_KEY].includes(e.key))refreshMetrics()});document.addEventListener('click',e=>{if(e.target.closest?.('[data-view="today"],#runImportBtn,#personalForm,#deletePersonalBtn'))setTimeout(refreshMetrics,80)},{passive:true});window.addEventListener('popstate',()=>setTimeout(refreshMetrics,80));setInterval(refreshMetrics,60000)}
function init(){injectStyles();injectModeLabels();buildDashboard();bindRefresh()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();