const LAYOUT_KEY='flow-university-dashboard-v1';
const TIMETABLE_KEY='flow-university-timetable-v1';
const PROFILE_KEY='flow-university-profile-v1';
const LONG_PRESS_MS=520;
const WIDGETS={
  next:{label:'다음 수업',defaultSize:'wide',sizes:['small','wide','large'],visible:true},
  today:{label:'오늘 수업',defaultSize:'small',sizes:['small','wide'],visible:true},
  semester:{label:'이번 학기',defaultSize:'small',sizes:['small','wide'],visible:true},
  schedule:{label:'오늘 일정',defaultSize:'large',sizes:['wide','large'],visible:true},
  campus:{label:'다음 강의실',defaultSize:'small',sizes:['small','wide'],visible:true},
  gap:{label:'빈 시간',defaultSize:'small',sizes:['small','wide'],visible:true},
  week:{label:'이번 주',defaultSize:'small',sizes:['small','wide'],visible:false},
  backup:{label:'내 데이터',defaultSize:'small',sizes:['small','wide'],visible:false},
};
const DEFAULT_ORDER=Object.keys(WIDGETS);
let editing=false,dragging=null,longPressTimer=null,longPressStart=null;
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
function read(key,fallback=null){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function write(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function todayIndex(){return(new Date().getDay()+6)%7}
function minuteText(n){if(!Number.isFinite(n))return'—';const h=Math.floor(n/60)%24,m=n%60;return`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`}
function timetable(){return read(TIMETABLE_KEY,null)}
function entries(){const tt=timetable();if(!tt?.subjects)return[];return tt.subjects.flatMap(subject=>(subject.times||[]).map(time=>({...time,subject,place:String(time.place||subject.place||'').trim()}))).filter(x=>Number.isFinite(x.day)&&Number.isFinite(x.startMinutes)&&Number.isFinite(x.endMinutes)).sort((a,b)=>a.day-b.day||a.startMinutes-b.startMinutes)}
function injectStyles(){if(document.querySelector('link[href="/university/dashboard.css"]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='/university/dashboard.css';document.head.append(link)}
function injectModeLabels(){$$('.brand').forEach(brand=>{if($('.brand-mode',brand))return;const mode=document.createElement('span');mode.className='brand-mode';mode.textContent='University';brand.append(mode)})}
function normalizedLayout(){const saved=read(LAYOUT_KEY,null);const byId=new Map(Array.isArray(saved)?saved.map(x=>[x.id,x]):[]);return DEFAULT_ORDER.map((id,index)=>{const m=WIDGETS[id],s=byId.get(id)||{};return{id,size:m.sizes.includes(s.size)?s.size:m.defaultSize,visible:typeof s.visible==='boolean'?s.visible:m.visible,order:Number.isFinite(s.order)?s.order:index}}).sort((a,b)=>a.order-b.order)}
function saveLayout(){const grid=$('#widgetDashboard');if(!grid)return;const state=$$('[data-widget-id]',grid).map((el,order)=>({id:el.dataset.widgetId,size:el.dataset.size||WIDGETS[el.dataset.widgetId]?.defaultSize||'small',visible:!el.classList.contains('widget-hidden'),order}));write(LAYOUT_KEY,state)}
function makeControls(el){if($('.widget-controls',el))return;const controls=document.createElement('div');controls.className='widget-controls';controls.innerHTML='<button class="widget-grab" type="button" aria-label="위젯 이동">⋮⋮</button><button class="widget-size" type="button" aria-label="위젯 크기 변경">크기</button><button class="widget-hide" type="button" aria-label="위젯 숨기기">×</button>';el.append(controls);$('.widget-size',controls).addEventListener('click',e=>{e.stopPropagation();cycleSize(el)});$('.widget-hide',controls).addEventListener('click',e=>{e.stopPropagation();el.classList.add('widget-hidden');saveLayout();refreshPicker()});const grab=$('.widget-grab',controls);grab.addEventListener('pointerdown',startDrag)}
function prepare(el,id){el.classList.add('dashboard-widget');el.dataset.widgetId=id;el.dataset.widgetLabel=WIDGETS[id].label;makeControls(el);bindLongPress(el);return el}
function customWidget(id,label,body){const el=document.createElement('article');el.className='summary-card dashboard-widget utility-widget';el.innerHTML=`<span>${esc(label)}</span>${body}`;return prepare(el,id)}
function buildDashboard(){const view=$('#todayView');if(!view||$('#widgetDashboard'))return;injectModeLabels();const summary=$('.summary-grid',view),content=$('.content-grid',view);if(!summary||!content)return;const summaryCards=[...summary.children],next=summaryCards[0],today=summaryCards[1],semester=summaryCards[2],schedule=$('.today-list-panel',content),importPanel=$('#emptyImportPanel');prepare(next,'next');prepare(today,'today');prepare(semester,'semester');prepare(schedule,'schedule');const campus=customWidget('campus','다음 강의실','<strong id="widgetCampusTitle">—</strong><p id="widgetCampusMeta">캠퍼스 이동을 확인합니다.</p><button class="widget-link" id="widgetCampusBtn" type="button">캠퍼스 보기</button>');const gap=customWidget('gap','빈 시간','<strong id="widgetGapTitle">—</strong><p id="widgetGapMeta">오늘 수업 사이</p>');const week=customWidget('week','이번 주','<strong id="widgetWeekTitle">—</strong><p id="widgetWeekMeta">주간 일정</p><button class="widget-link" id="widgetWeekBtn" type="button">시간표 보기</button>');const backup=customWidget('backup','내 데이터','<strong id="widgetBackupTitle">이 기기에 저장</strong><p id="widgetBackupMeta">JSON 백업 가능</p><button class="widget-link" id="widgetBackupBtn" type="button">백업 관리</button>');const grid=document.createElement('section');grid.id='widgetDashboard';grid.className='widget-dashboard';[next,today,semester,schedule,campus,gap,week,backup].forEach(x=>grid.append(x));summary.replaceWith(grid);content.classList.add('dashboard-import-wrap');if(schedule.parentElement===content)grid.append(schedule);if(importPanel&&importPanel.parentElement!==content)content.append(importPanel);const header=$('.hero-header',view),importBtn=$('#importTopBtn');if(header&&importBtn){const actions=document.createElement('div');actions.className='dashboard-top-actions';const edit=document.createElement('button');edit.id='dashboardEditBtn';edit.className='soft-button dashboard-edit-button';edit.type='button';edit.textContent='위젯 편집';actions.append(edit,importBtn);header.append(actions);edit.addEventListener('click',()=>setEditing(!editing))}const editor=document.createElement('div');editor.id='widgetEditorBar';editor.className='widget-editor-bar hidden';editor.innerHTML='<strong>대시보드 편집</strong><span>길게 누르거나 손잡이를 끌어 순서를 바꿀 수 있어요.</span><div><button class="soft-button" id="widgetAddBtn" type="button">+ 위젯</button><button class="soft-button" id="widgetResetBtn" type="button">초기화</button><button class="primary-button" id="widgetDoneBtn" type="button">완료</button></div>';grid.before(editor);$('#widgetAddBtn')?.addEventListener('click',openPicker);$('#widgetResetBtn')?.addEventListener('click',resetLayout);$('#widgetDoneBtn')?.addEventListener('click',()=>setEditing(false));$('#widgetCampusBtn')?.addEventListener('click',()=>openView('campus'));$('#widgetWeekBtn')?.addEventListener('click',()=>openView('timetable'));$('#widgetBackupBtn')?.addEventListener('click',()=>$('#changeUniversityBtn')?.click());ensurePicker();applyLayout();refreshMetrics()}
function openView(view){const b=document.querySelector(`[data-view="${view}"]`);if(b){b.click();return}if(view==='campus')location.href='/university/campus';if(view==='timetable')location.href='/university/timetable'}
function applyLayout(){const grid=$('#widgetDashboard');if(!grid)return;for(const item of normalizedLayout()){const el=grid.querySelector(`[data-widget-id="${item.id}"]`);if(!el)continue;el.dataset.size=item.size;el.classList.toggle('widget-hidden',!item.visible);grid.append(el)}refreshPicker()}
function setEditing(on){editing=Boolean(on);const view=$('#todayView');if(!view)return;view.classList.toggle('dashboard-editing',editing);$('#widgetEditorBar')?.classList.toggle('hidden',!editing);const btn=$('#dashboardEditBtn');if(btn)btn.textContent=editing?'편집 중':'위젯 편집';if(!editing){dragging=null;document.body.classList.remove('widget-drag-active');saveLayout()}}
function cycleSize(el){const meta=WIDGETS[el.dataset.widgetId],sizes=meta?.sizes||['small','wide','large'];const current=sizes.indexOf(el.dataset.size),next=sizes[(current+1)%sizes.length];el.dataset.size=next;saveLayout()}
function bindLongPress(el){el.addEventListener('pointerdown',e=>{if(editing||e.button!==0||e.target.closest('.widget-controls,button,a'))return;longPressStart={x:e.clientX,y:e.clientY};clearTimeout(longPressTimer);longPressTimer=setTimeout(()=>{setEditing(true);try{navigator.vibrate?.(18)}catch{}},LONG_PRESS_MS)});el.addEventListener('pointermove',e=>{if(!longPressStart)return;if(Math.hypot(e.clientX-longPressStart.x,e.clientY-longPressStart.y)>10){clearTimeout(longPressTimer);longPressStart=null}});['pointerup','pointercancel','pointerleave'].forEach(type=>el.addEventListener(type,()=>{clearTimeout(longPressTimer);longPressStart=null}))}
function startDrag(e){if(!editing)return;e.preventDefault();const widget=e.currentTarget.closest('[data-widget-id]');if(!widget)return;dragging=widget;widget.classList.add('widget-dragging');document.body.classList.add('widget-drag-active');e.currentTarget.setPointerCapture?.(e.pointerId);document.addEventListener('pointermove',dragMove);document.addEventListener('pointerup',endDrag,{once:true});document.addEventListener('pointercancel',endDrag,{once:true})}
function dragMove(e){if(!dragging)return;const target=document.elementFromPoint(e.clientX,e.clientY)?.closest?.('[data-widget-id]');if(!target||target===dragging||target.parentElement!==dragging.parentElement||target.classList.contains('widget-hidden'))return;const r=target.getBoundingClientRect(),before=e.clientY<r.top+r.height/2||(Math.abs(e.clientY-(r.top+r.height/2))<r.height*.22&&e.clientX<r.left+r.width/2);target.parentElement.insertBefore(dragging,before?target:target.nextSibling)}
function endDrag(){if(dragging)dragging.classList.remove('widget-dragging');dragging=null;document.body.classList.remove('widget-drag-active');document.removeEventListener('pointermove',dragMove);saveLayout()}
function ensurePicker(){if($('#widgetPicker'))return;const d=document.createElement('dialog');d.id='widgetPicker';d.innerHTML='<div class="dialog-sheet widget-picker-sheet"><button class="dialog-close" data-widget-picker-close type="button" aria-label="닫기">×</button><span class="kicker">WIDGETS</span><h2>위젯 추가</h2><p>필요한 정보만 오늘 화면에 올려둘 수 있습니다.</p><div class="widget-picker-list" id="widgetPickerList"></div></div>';document.body.append(d);$('[data-widget-picker-close]',d).addEventListener('click',()=>d.close())}
function openPicker(){ensurePicker();refreshPicker();const d=$('#widgetPicker');if(d&&!d.open)d.showModal()}
function refreshPicker(){const box=$('#widgetPickerList');if(!box)return;const grid=$('#widgetDashboard');box.innerHTML=DEFAULT_ORDER.map(id=>{const el=grid?.querySelector(`[data-widget-id="${id}"]`),shown=el&&!el.classList.contains('widget-hidden');return`<button class="widget-picker-item${shown?' is-added':''}" type="button" data-picker-id="${id}"><span><strong>${esc(WIDGETS[id].label)}</strong><small>${shown?'오늘 화면에 표시 중':'탭해서 추가'}</small></span><b>${shown?'✓':'+'}</b></button>`}).join('');$$('[data-picker-id]',box).forEach(btn=>btn.addEventListener('click',()=>{const el=grid?.querySelector(`[data-widget-id="${btn.dataset.pickerId}"]`);if(!el)return;el.classList.toggle('widget-hidden');saveLayout();refreshPicker()}))}
function resetLayout(){localStorage.removeItem(LAYOUT_KEY);applyLayout();setEditing(true)}
function refreshMetrics(){const tt=timetable(),all=entries(),day=all.filter(x=>x.day===todayIndex()),now=new Date(),mins=now.getHours()*60+now.getMinutes();const upcoming=day.find(x=>x.startMinutes>mins&&x.place);const campusTitle=$('#widgetCampusTitle'),campusMeta=$('#widgetCampusMeta');if(campusTitle){campusTitle.textContent=upcoming?.place||'오늘 이동 없음';campusMeta.textContent=upcoming?[upcoming.start,upcoming.subject?.name].filter(Boolean).join(' · '):'남은 강의실 이동이 없습니다.'}let gap=null;for(let i=0;i<day.length-1;i++){const a=day[i],b=day[i+1],duration=b.startMinutes-a.endMinutes;if(duration>=20&&a.endMinutes>=mins-5){gap={start:a.endMinutes,end:b.startMinutes,duration};break}}const gapTitle=$('#widgetGapTitle'),gapMeta=$('#widgetGapMeta');if(gapTitle){gapTitle.textContent=gap?`${gap.duration}분`:(tt?'여유 없음':'—');gapMeta.textContent=gap?`${minuteText(gap.start)}–${minuteText(gap.end)}`:(tt?'20분 이상 공강 없음':'시간표를 가져오세요')}const weekTitle=$('#widgetWeekTitle'),weekMeta=$('#widgetWeekMeta');if(weekTitle){const subjects=tt?.subjects?.length||0;weekTitle.textContent=tt?`${all.length}개 일정`:'—';weekMeta.textContent=tt?`${subjects}개 과목 · ${tt.year||''} ${tt.semester||''}`.trim():'시간표 미등록'}const profile=read(PROFILE_KEY,null);const backupMeta=$('#widgetBackupMeta');if(backupMeta)backupMeta.textContent=profile?`${profile.name||'대학교'} · 백업 저장 가능`:'대학을 먼저 선택하세요'}
function bindRefresh(){window.addEventListener('flow:timetable-changed',refreshMetrics);window.addEventListener('storage',e=>{if([TIMETABLE_KEY,PROFILE_KEY,LAYOUT_KEY].includes(e.key))refreshMetrics()});document.addEventListener('click',e=>{if(e.target.closest?.('[data-view="today"],#runImportBtn,#personalForm,#deletePersonalBtn'))setTimeout(refreshMetrics,80)},{passive:true});window.addEventListener('popstate',()=>setTimeout(refreshMetrics,80));setInterval(refreshMetrics,60000)}
function init(){injectStyles();injectModeLabels();buildDashboard();bindRefresh()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();