if(!document.querySelector('link[data-flow-timetable-enhance]')){const l=document.createElement('link');l.rel='stylesheet';l.href='/university/timetable-enhance.css';l.dataset.flowTimetableEnhance='1';document.head.append(l)}
const TIMETABLE_KEY='flow-university-timetable-v1';
const OVERRIDE_KEY='flow-university-time-overrides-v1';
const DAY_NAMES=['월','화','수','목','금','토','일'];
const RESIZE_STEP_MINUTES=5;
const RESIZE_MIN_DURATION=15;
let active=null,applying=false,renderTimer=null,timeResize=null;

function read(key,fallback=null){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function write(key,value){localStorage.setItem(key,JSON.stringify(value))}
function mins(value){const [h,m]=String(value||'').split(':').map(Number);return Number.isFinite(h)&&Number.isFinite(m)?h*60+m:NaN}
function timeText(value){const n=Math.max(0,Math.min(1439,Number(value)||0));return`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
function snapMinutes(value){return Math.round(Number(value)/RESIZE_STEP_MINUTES)*RESIZE_STEP_MINUTES}
function norm(v=''){return String(v).replace(/\s+/g,'').toLowerCase()}
function original(time,key,fallback){return time?.[key]??fallback}
function signature(subject,time){const start=original(time,'flowOriginalStart',time.start),end=original(time,'flowOriginalEnd',time.end);return [norm(subject?.name),norm(subject?.professor),Number(time?.day),start,end,norm(time?.place||subject?.place)].join('|')}
function effectiveMatch(subject,time,target){return norm(subject?.name)===norm(target.name)&&Number(time?.day)===Number(target.day)&&String(time?.start)===String(target.start)&&String(time?.end)===String(target.end)}
function notify(){window.dispatchEvent(new CustomEvent('flow:timetable-changed'))}
function applyOverrides(){if(applying)return;const tt=read(TIMETABLE_KEY,null),overrides=read(OVERRIDE_KEY,[]);if(!tt?.subjects?.length||!Array.isArray(overrides)||!overrides.length)return;let changed=false;for(const subject of tt.subjects){if(subject?.custom)continue;for(const time of subject.times||[]){const key=signature(subject,time),o=overrides.find(x=>x.key===key);if(!o)continue;const os=original(time,'flowOriginalStart',time.start),oe=original(time,'flowOriginalEnd',time.end),osm=original(time,'flowOriginalStartMinutes',time.startMinutes),oem=original(time,'flowOriginalEndMinutes',time.endMinutes);if(time.flowOriginalStart==null){time.flowOriginalStart=os;time.flowOriginalEnd=oe;time.flowOriginalStartMinutes=osm;time.flowOriginalEndMinutes=oem;changed=true}if(time.start!==o.start||time.end!==o.end||time.startMinutes!==o.startMinutes||time.endMinutes!==o.endMinutes||!time.flowTimeOverride){time.start=o.start;time.end=o.end;time.startMinutes=o.startMinutes;time.endMinutes=o.endMinutes;time.flowTimeOverride=true;changed=true}}}if(changed){applying=true;write(TIMETABLE_KEY,tt);queueMicrotask(()=>{notify();applying=false})}}
function ensureDialog(){if(document.querySelector('#classTimeDialog'))return;const d=document.createElement('dialog');d.id='classTimeDialog';d.innerHTML=`<form class="dialog-sheet class-time-sheet" id="classTimeForm"><button class="dialog-close" type="button" data-class-time-close aria-label="닫기">×</button><span class="kicker">CLASS TIME</span><h2 id="classTimeTitle">수업 시간 수정</h2><p id="classTimeInfo">가져온 원본은 유지하고 실제 수업 시간만 보정합니다.</p><div class="class-time-original" id="classTimeOriginal"></div><div class="personal-time-row"><label class="dialog-field">시작<input id="classTimeStart" type="time" step="300" required></label><label class="dialog-field">종료<input id="classTimeEnd" type="time" step="300" required></label></div><div class="class-time-quick"><button type="button" data-end-delta="-5">종료 -5분</button><button type="button" data-end-delta="-10">종료 -10분</button><button type="button" data-end-delta="5">종료 +5분</button></div><p class="class-time-note">이 요일의 수업 시간 블록에만 적용됩니다. 에브리타임을 다시 가져와도 유지됩니다.</p><div class="personal-dialog-actions"><button class="soft-button" id="classTimeReset" type="button">원래 시간</button><button class="primary-button" type="submit">적용</button></div></form>`;document.body.append(d);d.querySelector('[data-class-time-close]').addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d)d.close()});d.querySelectorAll('[data-end-delta]').forEach(b=>b.addEventListener('click',()=>{const input=d.querySelector('#classTimeEnd'),next=mins(input.value)+Number(b.dataset.endDelta);if(Number.isFinite(next)){input.value=timeText(next);input.classList.add('time-pulse');setTimeout(()=>input.classList.remove('time-pulse'),180)}}));d.querySelector('#classTimeForm').addEventListener('submit',saveActive);d.querySelector('#classTimeReset').addEventListener('click',resetActive)}
function parseBlock(block){const column=block.closest('.day-column'),day=Number(column?.dataset.gridDay);const title=String(block.getAttribute('title')||'');const m=title.match(/^(.*)\s(\d{2}:\d{2})-(\d{2}:\d{2})$/);if(!m||!Number.isFinite(day))return null;return{name:m[1].trim(),day,start:m[2],end:m[3]}}
function findTarget(meta){const tt=read(TIMETABLE_KEY,null);if(!tt?.subjects)return null;for(let si=0;si<tt.subjects.length;si++){const subject=tt.subjects[si];if(subject?.custom)continue;for(let ti=0;ti<(subject.times||[]).length;ti++){const time=subject.times[ti];if(effectiveMatch(subject,time,meta))return{tt,subject,time,si,ti}}}return null}
function openEditor(block){const meta=parseBlock(block),target=meta&&findTarget(meta);if(!target)return;ensureDialog();active={...target,key:signature(target.subject,target.time)};const d=document.querySelector('#classTimeDialog'),origStart=original(target.time,'flowOriginalStart',target.time.start),origEnd=original(target.time,'flowOriginalEnd',target.time.end);d.querySelector('#classTimeTitle').textContent=target.subject.name||'수업 시간 수정';d.querySelector('#classTimeInfo').textContent=[DAY_NAMES[target.time.day],target.time.place||target.subject.place,target.subject.professor].filter(Boolean).join(' · ');d.querySelector('#classTimeOriginal').textContent=`원래 ${origStart}–${origEnd}${target.time.flowTimeOverride?` · 현재 ${target.time.start}–${target.time.end}`:''}`;d.querySelector('#classTimeStart').value=target.time.start;d.querySelector('#classTimeEnd').value=target.time.end;if(!d.open)d.showModal()}
function persistTimeOverride(target,start,end){const sm=mins(start),em=mins(end);if(!target||!Number.isFinite(sm)||!Number.isFinite(em)||em<=sm)return false;const tt=read(TIMETABLE_KEY,null),subject=tt?.subjects?.[target.si],time=subject?.times?.[target.ti];if(!subject||!time)return false;const origStart=original(time,'flowOriginalStart',time.start),origEnd=original(time,'flowOriginalEnd',time.end),origSm=original(time,'flowOriginalStartMinutes',time.startMinutes),origEm=original(time,'flowOriginalEndMinutes',time.endMinutes);time.flowOriginalStart=origStart;time.flowOriginalEnd=origEnd;time.flowOriginalStartMinutes=origSm;time.flowOriginalEndMinutes=origEm;time.start=start;time.end=end;time.startMinutes=sm;time.endMinutes=em;time.flowTimeOverride=true;const key=signature(subject,time),list=read(OVERRIDE_KEY,[]).filter(x=>x.key!==key);list.push({key,start,end,startMinutes:sm,endMinutes:em,updatedAt:Date.now()});write(OVERRIDE_KEY,list);write(TIMETABLE_KEY,tt);notify();scheduleDecorate(40);return true}
function saveActive(event){event.preventDefault();if(!active)return;const start=document.querySelector('#classTimeStart').value,end=document.querySelector('#classTimeEnd').value;if(!persistTimeOverride(active,start,end))return;document.querySelector('#classTimeDialog')?.close()}
function resetActive(){if(!active)return;const tt=read(TIMETABLE_KEY,null),subject=tt?.subjects?.[active.si],time=subject?.times?.[active.ti];if(!subject||!time)return;const key=signature(subject,time),start=original(time,'flowOriginalStart',time.start),end=original(time,'flowOriginalEnd',time.end),sm=original(time,'flowOriginalStartMinutes',time.startMinutes),em=original(time,'flowOriginalEndMinutes',time.endMinutes);time.start=start;time.end=end;time.startMinutes=sm;time.endMinutes=em;delete time.flowOriginalStart;delete time.flowOriginalEnd;delete time.flowOriginalStartMinutes;delete time.flowOriginalEndMinutes;delete time.flowTimeOverride;write(OVERRIDE_KEY,read(OVERRIDE_KEY,[]).filter(x=>x.key!==key));write(TIMETABLE_KEY,tt);document.querySelector('#classTimeDialog')?.close();notify();scheduleDecorate(40)}
function resizeGridEnd(block,hourPx){const grid=block.closest('#timeGrid')||document.querySelector('#timeGrid'),column=block.closest('.day-column'),first=grid?.querySelector('.hour-label'),gridStart=mins(first?.textContent?.trim());if(!column||!Number.isFinite(gridStart)||!Number.isFinite(hourPx)||hourPx<=0)return 1439;const span=(column.clientHeight/hourPx)*60;return Math.min(1439,Math.floor((gridStart+span)/RESIZE_STEP_MINUTES)*RESIZE_STEP_MINUTES)}
function beginTimeResize(event){if(!event.isPrimary||event.button!==0||timeResize)return;const handle=event.target.closest?.('[data-time-resize-handle]'),block=handle?.closest?.('#timeGrid .course-block.flow-editable-class:not(.custom)');if(!handle||!block)return;const meta=parseBlock(block),target=meta&&findTarget(meta),grid=block.closest('#timeGrid')||document.querySelector('#timeGrid'),hourPx=parseFloat(getComputedStyle(grid).getPropertyValue('--hour'))||72,box=block.getBoundingClientRect();if(!target||!box.height||!Number.isFinite(target.time.startMinutes)||!Number.isFinite(target.time.endMinutes)||!hourPx)return;event.preventDefault();event.stopPropagation();try{handle.setPointerCapture?.(event.pointerId)}catch{}const label=block.querySelector('.flow-course-time'),readout=block.querySelector('.flow-time-resize-readout');timeResize={id:event.pointerId,handle,block,si:target.si,ti:target.ti,startY:event.clientY,startMinutes:Number(target.time.startMinutes),startText:String(target.time.start),startEndMinutes:Number(target.time.endMinutes),currentEndMinutes:Number(target.time.endMinutes),hourPx,originalHeight:block.style.height,originalLabel:label?.textContent||'',label,readout,maxEnd:resizeGridEnd(block,hourPx)};block.classList.add('flow-time-resizing');block.dataset.timeResizing='true';if(readout)readout.textContent=String(target.time.end)}
function previewTimeResize(event){const state=timeResize;if(!state||event.pointerId!==state.id)return;event.preventDefault();const rawEnd=state.startEndMinutes+((event.clientY-state.startY)/state.hourPx)*60,minEnd=state.startMinutes+RESIZE_MIN_DURATION,next=Math.max(minEnd,Math.min(state.maxEnd,snapMinutes(rawEnd))),height=Math.max(22,((next-state.startMinutes)/60)*state.hourPx),end=timeText(next);state.currentEndMinutes=next;state.block.style.height=`${height}px`;if(state.label)state.label.textContent=`${state.startText}–${end}`;if(state.readout)state.readout.textContent=end;state.block.dataset.timeResizeEnd=end}
function finishTimeResize(cancel=false){const state=timeResize;if(!state)return;timeResize=null;try{if(state.handle?.hasPointerCapture?.(state.id))state.handle.releasePointerCapture(state.id)}catch{}state.block.classList.remove('flow-time-resizing');state.block.removeAttribute('data-time-resizing');state.block.removeAttribute('data-time-resize-end');if(cancel){state.block.style.height=state.originalHeight;if(state.label)state.label.textContent=state.originalLabel;if(state.readout)state.readout.textContent='';return}if(state.currentEndMinutes===state.startEndMinutes){state.block.style.height=state.originalHeight;if(state.label)state.label.textContent=state.originalLabel;if(state.readout)state.readout.textContent='';return}persistTimeOverride({si:state.si,ti:state.ti},state.startText,timeText(state.currentEndMinutes))}
function onTimeResizeEnd(event){const state=timeResize;if(!state||event.pointerId!==state.id)return;event.preventDefault();finishTimeResize(event.type==='pointercancel')}
function decorateBlocks(){const grid=document.querySelector('#timeGrid');if(!grid)return;const today=(new Date().getDay()+6)%7;grid.querySelectorAll('.grid-header-cell[data-grid-day]').forEach(h=>h.classList.toggle('flow-today',Number(h.dataset.gridDay)===today));grid.querySelectorAll('.day-column').forEach(c=>c.classList.toggle('flow-today',Number(c.dataset.gridDay)===today));grid.querySelectorAll('.course-block').forEach(block=>{const meta=parseBlock(block);if(!meta)return;if(!block.classList.contains('custom')){block.classList.add('flow-editable-class');block.setAttribute('role','button');block.setAttribute('tabindex','0');block.setAttribute('aria-label',`${meta.name} ${meta.start}부터 ${meta.end}. 시간 수정`);if(!block.querySelector('[data-time-resize-handle]')){const handle=document.createElement('span');handle.className='flow-time-resize-handle';handle.dataset.timeResizeHandle='';handle.setAttribute('aria-hidden','true');block.append(handle)}if(!block.querySelector('.flow-time-resize-readout')){const readout=document.createElement('span');readout.className='flow-time-resize-readout';readout.setAttribute('aria-hidden','true');block.append(readout)}}let label=block.querySelector('.flow-course-time');if(!label){label=document.createElement('span');label.className='flow-course-time';block.append(label)}label.textContent=`${meta.start}–${meta.end}`});renderNowLine()}
function renderNowLine(){document.querySelectorAll('.flow-now-line').forEach(x=>x.remove());const grid=document.querySelector('#timeGrid'),body=grid?.querySelector('.grid-body');if(!grid||!body)return;const today=(new Date().getDay()+6)%7,column=body.querySelector(`.day-column[data-grid-day="${today}"]`);if(!column)return;const first=grid.querySelector('.hour-label'),hourPx=parseFloat(getComputedStyle(grid).getPropertyValue('--hour'))||72;if(!first)return;const start=mins(first.textContent.trim()),now=new Date(),current=now.getHours()*60+now.getMinutes(),top=((current-start)/60)*hourPx;if(!Number.isFinite(top)||top<0||top>column.clientHeight)return;const line=document.createElement('div');line.className='flow-now-line';line.style.top=`${top}px`;line.innerHTML=`<span>${timeText(current)}</span>`;column.append(line)}
function scheduleDecorate(delay=60){clearTimeout(renderTimer);renderTimer=setTimeout(decorateBlocks,delay)}
document.addEventListener('pointerdown',beginTimeResize,{passive:false});document.addEventListener('pointermove',previewTimeResize,{passive:false});document.addEventListener('pointerup',onTimeResizeEnd,{passive:false});document.addEventListener('pointercancel',onTimeResizeEnd,{passive:false});window.addEventListener('blur',()=>finishTimeResize(true));document.addEventListener('click',e=>{if(e.target.closest?.('[data-time-resize-handle]')){e.preventDefault();e.stopPropagation();return}const block=e.target.closest?.('#timeGrid .course-block.flow-editable-class:not(.custom)');if(block){e.preventDefault();openEditor(block);return}if(e.target.closest?.('[data-view="timetable"],[data-go="timetable"]'))scheduleDecorate(80)},{passive:false});document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches?.('#timeGrid .course-block.flow-editable-class:not(.custom)')){e.preventDefault();openEditor(e.target)}});window.addEventListener('flow:timetable-changed',()=>{if(timeResize)finishTimeResize(true);setTimeout(applyOverrides,0);scheduleDecorate(80)});window.addEventListener('resize',()=>{if(timeResize)finishTimeResize(true);scheduleDecorate(180)},{passive:true});setInterval(()=>{if(!document.querySelector('#timetableView.hidden'))renderNowLine()},60000);ensureDialog();applyOverrides();scheduleDecorate(120);
