if(!document.querySelector('link[data-flow-timetable-enhance]')){const l=document.createElement('link');l.rel='stylesheet';l.href='/university/timetable-enhance.css';l.dataset.flowTimetableEnhance='1';document.head.append(l)}
const TIMETABLE_KEY='flow-university-timetable-v1';
const OVERRIDE_KEY='flow-university-time-overrides-v1';
const DAY_NAMES=['월','화','수','목','금','토','일'];
const RESIZE_STEP_MINUTES=5;
const RESIZE_MIN_DURATION=15;
const RESIZE_MOVE_THRESHOLD=6;
let active=null,applying=false,renderTimer=null,timeResize=null,selectedTimeKey=null,suppressTimeClickUntil=0;

function read(key,fallback=null){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function write(key,value){localStorage.setItem(key,JSON.stringify(value))}
function mins(value){const [h,m]=String(value||'').split(':').map(Number);return Number.isFinite(h)&&Number.isFinite(m)?h*60+m:NaN}
function timeText(value){const n=Math.max(0,Math.min(1439,Number(value)||0));return`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
function snapMinutes(value){return Math.round(Number(value)/RESIZE_STEP_MINUTES)*RESIZE_STEP_MINUTES}
function norm(v=''){return String(v).replace(/\s+/g,'').toLowerCase()}
function original(time,key,fallback){return time?.[key]??fallback}
function signature(subject,time){const start=original(time,'flowOriginalStart',time.start),end=original(time,'flowOriginalEnd',time.end);return [norm(subject?.name),norm(subject?.professor),Number(time?.day),start,end,norm(time?.place||subject?.place)].join('|')}
function effectiveMatch(subject,time,target){return norm(subject?.name)===norm(target.name)&&Number(time?.day)===Number(target.day)&&String(time?.start)===String(target.start)&&String(time?.end)===String(target.end)}
function notify(){window.dispatchEvent(new CustomEvent('flow:timetable-changed'))}
function applyOverrides(){if(applying)return;const tt=read(TIMETABLE_KEY,null),overrides=read(OVERRIDE_KEY,[]);if(!tt?.subjects?.length||!Array.isArray(overrides)||!overrides.length)return;let changed=false;for(const subject of tt.subjects){if(subject?.custom)continue;for(const time of subject.times||[]){const key=signature(subject,time),o=overrides.find(x=>x.key===key);if(!o)continue;const os=original(time,'flowOriginalStart',time.start),oe=original(time,'flowOriginalEnd',time.end),osm=original(time,'flowOriginalStartMinutes',time.startMinutes),oem=original(time,'flowOriginalEndMinutes',time.endMinutes);if(time.flowOriginalStart==null){time.flowOriginalStart=os;time.flowOriginalEnd=oe;time.flowOriginalStartMinutes=osm;time.flowOriginalEndMinutes=oem;changed=true}if(time.start!==o.start||time.end!==o.end||time.startMinutes!==o.startMinutes||time.endMinutes!==o.endMinutes||!time.flowTimeOverride){time.start=o.start;time.end=o.end;time.startMinutes=o.startMinutes;time.endMinutes=o.endMinutes;time.flowTimeOverride=true;changed=true}}}if(changed){applying=true;write(TIMETABLE_KEY,tt);queueMicrotask(()=>{notify();applying=false})}}

function ensureDialog(){if(document.querySelector('#classTimeDialog'))return;const d=document.createElement('dialog');d.id='classTimeDialog';d.innerHTML=`<form class="dialog-sheet class-time-sheet" id="classTimeForm"><button class="dialog-close" type="button" data-class-time-close aria-label="닫기">×</button><span class="kicker">CLASS TIME</span><h2 id="classTimeTitle">수업 시간 수정</h2><p id="classTimeInfo">가져온 원본은 유지하고 실제 수업 시간만 보정합니다.</p><div class="class-time-original" id="classTimeOriginal"></div><div class="personal-time-row"><label class="dialog-field">시작<input id="classTimeStart" type="time" step="300" required></label><label class="dialog-field">종료<input id="classTimeEnd" type="time" step="300" required></label></div><div class="class-time-quick"><button type="button" data-end-delta="-5">종료 -5분</button><button type="button" data-end-delta="-10">종료 -10분</button><button type="button" data-end-delta="5">종료 +5분</button></div><p class="class-time-note">이 요일의 수업 시간 블록에만 적용됩니다. 에브리타임을 다시 가져와도 유지됩니다.</p><div class="personal-dialog-actions"><button class="soft-button" id="classTimeReset" type="button">원래 시간</button><button class="primary-button" type="submit">적용</button></div></form>`;document.body.append(d);d.querySelector('[data-class-time-close]').addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d)d.close()});d.querySelectorAll('[data-end-delta]').forEach(b=>b.addEventListener('click',()=>{const input=d.querySelector('#classTimeEnd'),next=mins(input.value)+Number(b.dataset.endDelta);if(Number.isFinite(next)){input.value=timeText(next);input.classList.add('time-pulse');setTimeout(()=>input.classList.remove('time-pulse'),180)}}));d.querySelector('#classTimeForm').addEventListener('submit',saveActive);d.querySelector('#classTimeReset').addEventListener('click',resetActive)}
function parseBlock(block){const column=block.closest('.day-column'),day=Number(column?.dataset.gridDay);const title=String(block.getAttribute('title')||'');const m=title.match(/^(.*)\s(\d{2}:\d{2})-(\d{2}:\d{2})$/);if(!m||!Number.isFinite(day))return null;return{name:m[1].trim(),day,start:m[2],end:m[3]}}
function findTarget(meta){const tt=read(TIMETABLE_KEY,null);if(!tt?.subjects)return null;for(let si=0;si<tt.subjects.length;si++){const subject=tt.subjects[si];if(subject?.custom)continue;for(let ti=0;ti<(subject.times||[]).length;ti++){const time=subject.times[ti];if(effectiveMatch(subject,time,meta))return{tt,subject,time,si,ti}}}return null}
function targetForBlock(block){const meta=parseBlock(block),target=meta&&findTarget(meta);return target?{meta,target,key:signature(target.subject,target.time)}:null}

function updateBlockA11y(block,selected=false){const meta=parseBlock(block);if(!meta)return;block.setAttribute('role','button');block.setAttribute('tabindex','0');block.setAttribute('aria-pressed',selected?'true':'false');block.setAttribute('aria-label',selected?`${meta.name} ${meta.start}부터 ${meta.end}. 선택됨. 오른쪽 가장자리를 위아래로 드래그해 시간을 조절하거나 다시 눌러 상세 편집`:`${meta.name} ${meta.start}부터 ${meta.end}. 눌러 시간 조절 선택`)}
function ensureSelectionRail(block){let rail=block.querySelector('[data-time-selection-rail]');if(rail)return rail;rail=document.createElement('span');rail.className='flow-time-selection-rail';rail.dataset.timeSelectionRail='';rail.setAttribute('aria-hidden','true');block.append(rail);return rail}
function clearBlockSelection(block){block.classList.remove('flow-time-selected','flow-time-armed');block.removeAttribute('data-time-selected');block.removeAttribute('data-time-resize-armed');block.removeAttribute('data-time-resize-edge');block.querySelector('[data-time-selection-rail]')?.remove();updateBlockA11y(block,false)}
function clearSelection({keepKey=false}={}){document.querySelectorAll('#timeGrid .course-block.flow-time-selected').forEach(clearBlockSelection);if(!keepKey)selectedTimeKey=null}
function selectBlock(block,{focus=false}={}){const info=targetForBlock(block);if(!info)return false;selectedTimeKey=info.key;document.querySelectorAll('#timeGrid .course-block.flow-editable-class:not(.custom)').forEach(other=>{if(other!==block&&other.classList.contains('flow-time-selected'))clearBlockSelection(other)});block.classList.add('flow-time-selected');block.dataset.timeSelected='true';ensureSelectionRail(block);updateBlockA11y(block,true);if(focus)block.focus({preventScroll:true});return true}

function openEditor(block){const info=targetForBlock(block);if(!info)return;ensureDialog();active={...info.target,key:info.key};const d=document.querySelector('#classTimeDialog'),origStart=original(info.target.time,'flowOriginalStart',info.target.time.start),origEnd=original(info.target.time,'flowOriginalEnd',info.target.time.end);d.querySelector('#classTimeTitle').textContent=info.target.subject.name||'수업 시간 수정';d.querySelector('#classTimeInfo').textContent=[DAY_NAMES[info.target.time.day],info.target.time.place||info.target.subject.place,info.target.subject.professor].filter(Boolean).join(' · ');d.querySelector('#classTimeOriginal').textContent=`원래 ${origStart}–${origEnd}${info.target.time.flowTimeOverride?` · 현재 ${info.target.time.start}–${info.target.time.end}`:''}`;d.querySelector('#classTimeStart').value=info.target.time.start;d.querySelector('#classTimeEnd').value=info.target.time.end;clearSelection();if(!d.open)d.showModal()}
function persistTimeOverride(target,start,end){const sm=mins(start),em=mins(end);if(!target||!Number.isFinite(sm)||!Number.isFinite(em)||em<=sm)return false;const tt=read(TIMETABLE_KEY,null),subject=tt?.subjects?.[target.si],time=subject?.times?.[target.ti];if(!subject||!time)return false;const origStart=original(time,'flowOriginalStart',time.start),origEnd=original(time,'flowOriginalEnd',time.end),origSm=original(time,'flowOriginalStartMinutes',time.startMinutes),origEm=original(time,'flowOriginalEndMinutes',time.endMinutes);time.flowOriginalStart=origStart;time.flowOriginalEnd=origEnd;time.flowOriginalStartMinutes=origSm;time.flowOriginalEndMinutes=origEm;time.start=start;time.end=end;time.startMinutes=sm;time.endMinutes=em;time.flowTimeOverride=true;const key=signature(subject,time),list=read(OVERRIDE_KEY,[]).filter(x=>x.key!==key);list.push({key,start,end,startMinutes:sm,endMinutes:em,updatedAt:Date.now()});write(OVERRIDE_KEY,list);write(TIMETABLE_KEY,tt);notify();scheduleDecorate(40);return true}
function saveActive(event){event.preventDefault();if(!active)return;const start=document.querySelector('#classTimeStart').value,end=document.querySelector('#classTimeEnd').value;if(!persistTimeOverride(active,start,end))return;document.querySelector('#classTimeDialog')?.close()}
function resetActive(){if(!active)return;const tt=read(TIMETABLE_KEY,null),subject=tt?.subjects?.[active.si],time=subject?.times?.[active.ti];if(!subject||!time)return;const key=signature(subject,time),start=original(time,'flowOriginalStart',time.start),end=original(time,'flowOriginalEnd',time.end),sm=original(time,'flowOriginalStartMinutes',time.startMinutes),em=original(time,'flowOriginalEndMinutes',time.endMinutes);time.start=start;time.end=end;time.startMinutes=sm;time.endMinutes=em;delete time.flowOriginalStart;delete time.flowOriginalEnd;delete time.flowOriginalStartMinutes;delete time.flowOriginalEndMinutes;delete time.flowTimeOverride;write(OVERRIDE_KEY,read(OVERRIDE_KEY,[]).filter(x=>x.key!==key));write(TIMETABLE_KEY,tt);document.querySelector('#classTimeDialog')?.close();notify();scheduleDecorate(40)}

function resizeGridBounds(block,hourPx){const grid=block.closest('#timeGrid')||document.querySelector('#timeGrid'),column=block.closest('.day-column'),first=grid?.querySelector('.hour-label'),gridStart=mins(first?.textContent?.trim());if(!column||!Number.isFinite(gridStart)||!Number.isFinite(hourPx)||hourPx<=0)return{minStart:0,maxEnd:1439};const span=(column.clientHeight/hourPx)*60;return{minStart:Math.max(0,Math.ceil(gridStart/RESIZE_STEP_MINUTES)*RESIZE_STEP_MINUTES),maxEnd:Math.min(1439,Math.floor((gridStart+span)/RESIZE_STEP_MINUTES)*RESIZE_STEP_MINUTES)}}
function resizeEdgeForPointer(block,clientY){const box=block.getBoundingClientRect();return Math.abs(clientY-box.top)<=Math.abs(box.bottom-clientY)?'start':'end'}
function beginTimeResize(event){if(!event.isPrimary||event.button!==0||timeResize)return;const rail=event.target.closest?.('[data-time-selection-rail]'),block=rail?.closest?.('#timeGrid .course-block.flow-editable-class.flow-time-selected:not(.custom)');if(!rail||!block)return;const info=targetForBlock(block),grid=block.closest('#timeGrid')||document.querySelector('#timeGrid'),hourPx=parseFloat(getComputedStyle(grid).getPropertyValue('--hour'))||72,box=block.getBoundingClientRect();if(!info||!box.height||!Number.isFinite(info.target.time.startMinutes)||!Number.isFinite(info.target.time.endMinutes)||!hourPx)return;event.preventDefault();event.stopPropagation();const edge=resizeEdgeForPointer(block,event.clientY),label=block.querySelector('.flow-course-time'),bounds=resizeGridBounds(block,hourPx),topPx=parseFloat(block.style.top)||block.offsetTop||0;try{rail.setPointerCapture?.(event.pointerId)}catch{}timeResize={id:event.pointerId,rail,block,key:info.key,si:info.target.si,ti:info.target.ti,edge,startY:event.clientY,startMinutes:Number(info.target.time.startMinutes),endMinutes:Number(info.target.time.endMinutes),currentStartMinutes:Number(info.target.time.startMinutes),currentEndMinutes:Number(info.target.time.endMinutes),startText:String(info.target.time.start),endText:String(info.target.time.end),hourPx,originalTop:block.style.top,originalHeight:block.style.height,originalLabel:label?.textContent||'',topPx,label,bounds,moved:false};block.classList.add('flow-time-armed');block.dataset.timeResizeArmed=edge;rail.dataset.timeResizeEdge=edge}
function previewTimeResize(event){const state=timeResize;if(!state||event.pointerId!==state.id)return;const dy=event.clientY-state.startY;if(!state.moved&&Math.abs(dy)<RESIZE_MOVE_THRESHOLD)return;if(!state.moved){state.moved=true;state.block.classList.remove('flow-time-armed');state.block.classList.add('flow-time-resizing');state.block.dataset.timeResizing='true';state.block.dataset.timeResizeEdge=state.edge}event.preventDefault();const delta=(dy/state.hourPx)*60;if(state.edge==='start'){const rawStart=state.startMinutes+delta,maxStart=state.endMinutes-RESIZE_MIN_DURATION,next=Math.max(state.bounds.minStart,Math.min(maxStart,snapMinutes(rawStart))),height=Math.max(22,((state.endMinutes-next)/60)*state.hourPx),top=state.topPx+((next-state.startMinutes)/60)*state.hourPx,start=timeText(next);state.currentStartMinutes=next;state.block.style.top=`${top}px`;state.block.style.height=`${height}px`;if(state.label)state.label.textContent=`${start}–${state.endText}`;state.block.dataset.timeResizeStart=start}else{const rawEnd=state.endMinutes+delta,minEnd=state.startMinutes+RESIZE_MIN_DURATION,next=Math.max(minEnd,Math.min(state.bounds.maxEnd,snapMinutes(rawEnd))),height=Math.max(22,((next-state.startMinutes)/60)*state.hourPx),end=timeText(next);state.currentEndMinutes=next;state.block.style.height=`${height}px`;if(state.label)state.label.textContent=`${state.startText}–${end}`;state.block.dataset.timeResizeEnd=end}}
function restoreTimeResizePresentation(state){state.block.style.top=state.originalTop;state.block.style.height=state.originalHeight;if(state.label)state.label.textContent=state.originalLabel}
function finishTimeResize(cancel=false){const state=timeResize;if(!state)return;timeResize=null;try{if(state.rail?.hasPointerCapture?.(state.id))state.rail.releasePointerCapture(state.id)}catch{}state.block.classList.remove('flow-time-armed','flow-time-resizing');state.block.removeAttribute('data-time-resizing');state.block.removeAttribute('data-time-resize-armed');state.block.removeAttribute('data-time-resize-edge');state.block.removeAttribute('data-time-resize-start');state.block.removeAttribute('data-time-resize-end');state.rail?.removeAttribute('data-time-resize-edge');if(cancel||!state.moved){restoreTimeResizePresentation(state);return}const changed=state.edge==='start'?state.currentStartMinutes!==state.startMinutes:state.currentEndMinutes!==state.endMinutes;if(!changed){restoreTimeResizePresentation(state);return}selectedTimeKey=state.key;suppressTimeClickUntil=performance.now()+450;persistTimeOverride({si:state.si,ti:state.ti},timeText(state.currentStartMinutes),timeText(state.currentEndMinutes))}
function onTimeResizeEnd(event){const state=timeResize;if(!state||event.pointerId!==state.id)return;if(state.moved)event.preventDefault();finishTimeResize(event.type==='pointercancel')}

function decorateBlocks(){const grid=document.querySelector('#timeGrid');if(!grid)return;const today=(new Date().getDay()+6)%7;grid.querySelectorAll('.grid-header-cell[data-grid-day]').forEach(h=>h.classList.toggle('flow-today',Number(h.dataset.gridDay)===today));grid.querySelectorAll('.day-column').forEach(c=>c.classList.toggle('flow-today',Number(c.dataset.gridDay)===today));let selectedFound=false;grid.querySelectorAll('.course-block').forEach(block=>{const meta=parseBlock(block);if(!meta)return;if(!block.classList.contains('custom')){block.classList.add('flow-editable-class');const info=targetForBlock(block),selected=Boolean(info&&selectedTimeKey&&info.key===selectedTimeKey);if(selected){selectedFound=true;block.classList.add('flow-time-selected');block.dataset.timeSelected='true';ensureSelectionRail(block)}else{block.classList.remove('flow-time-selected','flow-time-armed');block.removeAttribute('data-time-selected');block.querySelector('[data-time-selection-rail]')?.remove()}updateBlockA11y(block,selected)}let label=block.querySelector('.flow-course-time');if(!label){label=document.createElement('span');label.className='flow-course-time';block.append(label)}label.textContent=`${meta.start}–${meta.end}`});if(selectedTimeKey&&!selectedFound)selectedTimeKey=null;renderNowLine()}
function renderNowLine(){document.querySelectorAll('.flow-now-line').forEach(x=>x.remove());const grid=document.querySelector('#timeGrid'),body=grid?.querySelector('.grid-body');if(!grid||!body)return;const today=(new Date().getDay()+6)%7,column=body.querySelector(`.day-column[data-grid-day="${today}"]`);if(!column)return;const first=grid.querySelector('.hour-label'),hourPx=parseFloat(getComputedStyle(grid).getPropertyValue('--hour'))||72;if(!first)return;const start=mins(first.textContent.trim()),now=new Date(),current=now.getHours()*60+now.getMinutes(),top=((current-start)/60)*hourPx;if(!Number.isFinite(top)||top<0||top>column.clientHeight)return;const line=document.createElement('div');line.className='flow-now-line';line.style.top=`${top}px`;line.innerHTML=`<span>${timeText(current)}</span>`;column.append(line)}
function scheduleDecorate(delay=60){clearTimeout(renderTimer);renderTimer=setTimeout(decorateBlocks,delay)}

document.addEventListener('pointerdown',beginTimeResize,{passive:false});
document.addEventListener('pointermove',previewTimeResize,{passive:false});
document.addEventListener('pointerup',onTimeResizeEnd,{passive:false});
document.addEventListener('pointercancel',onTimeResizeEnd,{passive:false});
window.addEventListener('blur',()=>finishTimeResize(true));
document.addEventListener('click',e=>{const rail=e.target.closest?.('[data-time-selection-rail]');if(rail){e.preventDefault();e.stopPropagation();return}const block=e.target.closest?.('#timeGrid .course-block.flow-editable-class:not(.custom)');if(block){e.preventDefault();if(performance.now()<suppressTimeClickUntil)return;if(block.classList.contains('flow-time-selected'))openEditor(block);else selectBlock(block);return}if(e.target.closest?.('[data-view="timetable"],[data-go="timetable"]')){scheduleDecorate(80);return}if(!e.target.closest?.('#classTimeDialog'))clearSelection()},{passive:false});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&selectedTimeKey){e.preventDefault();clearSelection();return}if((e.key==='Enter'||e.key===' ')&&e.target.matches?.('#timeGrid .course-block.flow-editable-class:not(.custom)')){e.preventDefault();openEditor(e.target)}});
window.addEventListener('flow:timetable-changed',()=>{if(timeResize)finishTimeResize(true);setTimeout(applyOverrides,0);scheduleDecorate(80)});
window.addEventListener('resize',()=>{if(timeResize)finishTimeResize(true);scheduleDecorate(180)},{passive:true});
setInterval(()=>{if(!document.querySelector('#timetableView.hidden'))renderNowLine()},60000);
ensureDialog();applyOverrides();scheduleDecorate(120);
