const EDGE='https://eicwcohfrvhwimwevzkd.supabase.co/functions/v1/university-data';
const EVENT_EDGE='https://eicwcohfrvhwimwevzkd.supabase.co/functions/v1/flow-quest-event';
const PROFILE_KEY='flow-university-profile-v1';
const TIMETABLE_KEY='flow-university-timetable-v1';
const MAJOR_KEY='flow-university-major-v1';
const THEME_KEY='flow-university-theme-v1';
const ANON_KEY='flow-university-anon-v1';
const SEEN_KEY='flow-university-seen-v1';
const ROUTE_TO_VIEW={'/university':'today','/university/':'today','/university/timetable':'timetable','/university/school':'school'};
const VIEW_TO_ROUTE={today:'/university',timetable:'/university/timetable',school:'/university/school'};
const DAY_NAMES=['월','화','수','목','금','토','일'];
const $=(s)=>document.querySelector(s);
const $$=(s)=>[...document.querySelectorAll(s)];

let profile=read(PROFILE_KEY,null);
let timetable=normalizeTimetable(read(TIMETABLE_KEY,null));
let major=read(MAJOR_KEY,null);
let profileData=null;
let profileLoadPromise=null;
let profileLoadError='';
let majors=[];
let searchTimer=null;
let searchAbort=null;
let currentView=ROUTE_TO_VIEW[location.pathname]||'today';
let toastTimer=null;
let resizeTimer=null;
let importDialogDismissedUntil=0;

function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function write(key,value){localStorage.setItem(key,JSON.stringify(value))}
function remove(key){localStorage.removeItem(key)}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]))}
function norm(v=''){return String(v).replace(/\s+/g,'').toLowerCase()}
function loading(on){$('#loadingBar')?.classList.toggle('active',on)}
function toast(message){const el=$('#toast');if(!el)return;el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),1900)}
function openDialog(id){const d=$(id);if(!d||d.open)return;if(id==='#importDialog'&&performance.now()<importDialogDismissedUntil)return;d.showModal()}
function closeDialog(d){if(!d)return;if(d.id==='importDialog')importDialogDismissedUntil=performance.now()+480;if(d.open)d.close()}
async function api(action,params={},options={}){const url=new URL(EDGE);url.searchParams.set('action',action);Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')url.searchParams.set(k,String(v))});const r=await fetch(url,{...options});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||'데이터를 불러오지 못했습니다.');return body}
function initial(name='U'){return name.replace(/대학교|대학$/g,'').trim().slice(0,1)||'U'}
function normalizeSemesterValue(value){const s=String(value??'').trim();if(!s)return'';if(/^\d+$/.test(s))return`${s}학기`;const m=s.match(/^([12])\s*(?:학기)?$/);if(m)return`${m[1]}학기`;return s}
function normalizeTimetable(value){if(!value||typeof value!=='object')return value;value.semester=normalizeSemesterValue(value.semester);value.subjects=Array.isArray(value.subjects)?value.subjects:[];return value}
function semesterText(){if(!timetable?.year)return'시간표 미등록';return`${timetable.year}년${timetable.semester?` ${normalizeSemesterValue(timetable.semester)}`:''}`}
function minutes(value){const [h,m]=String(value||'').split(':').map(Number);return Number.isFinite(h)&&Number.isFinite(m)?h*60+m:NaN}
function currentSemester(){const now=new Date();return{year:now.getFullYear(),semester:now.getMonth()<6?'1학기':'2학기'}}
function persistTimetable(){if(!timetable)return remove(TIMETABLE_KEY);timetable=normalizeTimetable(timetable);write(TIMETABLE_KEY,timetable);window.dispatchEvent(new CustomEvent('flow:timetable-changed'))}
function ensureTimetable(){if(timetable)return timetable;const current=currentSemester();timetable={source:'flow-personal',year:current.year,semester:current.semester,subjects:[]};persistTimetable();return timetable}
function requestPersistentStorage(){navigator.storage?.persist?.().catch(()=>{})}

const telemetryEnabled=!['localhost','127.0.0.1','::1'].includes(location.hostname);
let anonymousId=localStorage.getItem(ANON_KEY);
if(!anonymousId){anonymousId=crypto.randomUUID();localStorage.setItem(ANON_KEY,anonymousId)}
function trackUniversity(name){if(!telemetryEnabled)return;fetch(EVENT_EDGE,{method:'POST',headers:{'content-type':'application/json'},keepalive:true,body:JSON.stringify({event_name:`university_${name}`,anon_id:anonymousId})}).catch(()=>{})}
trackUniversity('page_view');
if(localStorage.getItem(SEEN_KEY))trackUniversity('return_visit');else localStorage.setItem(SEEN_KEY,String(Date.now()));

function showSetup(){profile=null;$('#setupView').classList.remove('hidden');$('#appView').classList.add('hidden');if(location.pathname!=='/university')history.replaceState({},'', '/university')}
function showApp(){if(!profile)return showSetup();$('#setupView').classList.add('hidden');$('#appView').classList.remove('hidden');requestPersistentStorage();renderIdentity();switchView(currentView,{push:false});void loadProfileData()}
function renderIdentity(){if(!profile)return;const name=profile.name||'대학교',mark=initial(name),majorName=major?.name||'학과 미선택';$('#sidebarUniversityName').textContent=name;$('#sidebarMajorName').textContent=majorName;$('#universityInitial').textContent=mark;$('#mobileUniversityName').textContent=name;$('#mobileSemester').textContent=semesterText();$('#profileInitial').textContent=mark;$('#profileTitle').textContent=`${name} 정보`;$('#profileName').textContent=name;$('#profileEnglish').textContent=profile.englishName||'';$('#profileAddress').textContent=profile.address||'';$('#profileType').textContent=[profile.foundation,profile.kind,profile.campus].filter(Boolean).join(' · ');$('#homepageLink').href=profile.homepage||'#';$('#homepageLink').classList.toggle('hidden',!profile.homepage);$('#changeCurrent').textContent=`현재 ${name}${major?.name?` · ${major.name}`:''}`;renderMajorDetail()}

function searchResults(schools,message='검색 결과가 없습니다.'){const box=$('#searchResults');if(!schools?.length){box.innerHTML=`<div class="search-state">${esc(message)}</div>`;box.classList.remove('hidden');return}box.innerHTML=schools.map((s,i)=>`<button class="result-button" type="button" data-school="${i}"><span><strong>${esc(s.name)}</strong><small>${esc([s.region,s.foundation,s.campus].filter(Boolean).join(' · '))}<br>${esc(s.address||'')}</small></span><span class="result-tag">${esc(s.kind||'대학교')}</span></button>`).join('');box.classList.remove('hidden');box.querySelectorAll('[data-school]').forEach(b=>b.addEventListener('click',()=>selectUniversity(schools[Number(b.dataset.school)])))}
async function runSearch(){const input=$('#universitySearch'),q=input.value.trim(),box=$('#searchResults');if(q.length<2){box.classList.add('hidden');box.innerHTML='';return}trackUniversity('search');searchAbort?.abort();searchAbort=new AbortController();box.classList.remove('hidden');box.innerHTML='<div class="search-state">대학 찾는 중…</div>';try{const r=await api('search',{q},{signal:searchAbort.signal});searchResults(r.schools)}catch(e){if(e.name!=='AbortError')searchResults([],e.message)}}
function queueSearch(){clearTimeout(searchTimer);searchTimer=setTimeout(runSearch,220)}
async function selectUniversity(school){trackUniversity('select');profile=school;major=null;timetable=null;profileData=null;profileLoadError='';majors=[];write(PROFILE_KEY,profile);remove(MAJOR_KEY);remove(TIMETABLE_KEY);currentView='today';showApp();history.replaceState({},'', '/university');toast(`${school.name} 저장됨`);setTimeout(()=>openDialog('#importDialog'),180)}

function switchView(view,{push=true}={}){if(!VIEW_TO_ROUTE[view])view='today';currentView=view;$$('[data-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.panel!==view));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(push&&location.pathname!==VIEW_TO_ROUTE[view])history.pushState({view},'',VIEW_TO_ROUTE[view]);if(view==='today')renderToday();if(view==='timetable')renderTimetable();if(view==='school'){renderProfile();void loadProfileData()}}
window.addEventListener('popstate',()=>switchView(ROUTE_TO_VIEW[location.pathname]||'today',{push:false}));

function entries(){if(!timetable?.subjects)return[];return timetable.subjects.flatMap((subject,subjectIndex)=>(subject.times||[]).map(time=>({...time,subject,subjectIndex}))).filter(x=>Number.isFinite(x.day)&&Number.isFinite(x.startMinutes)&&Number.isFinite(x.endMinutes)).sort((a,b)=>a.day-b.day||a.startMinutes-b.startMinutes)}
function dayEntries(day){return entries().filter(x=>x.day===day)}
function todayIndex(){return(new Date().getDay()+6)%7}
function timeLabel(start,end){return`${start}–${end}`}
function renderToday(){renderIdentity();const day=todayIndex(),list=dayEntries(day),now=new Date(),mins=now.getHours()*60+now.getMinutes();$('#todayTitle').textContent=`${DAY_NAMES[day]}요일 수업`;$('#todaySubtitle').textContent=profile?`${profile.name}${major?.name?` · ${major.name}`:''}`:'시간표를 가져오면 오늘 수업을 바로 보여줍니다.';$('#todayCount').textContent=timetable?`${list.length}개`:'—';$('#todayCountMeta').textContent=timetable?'오늘 등록된 일정':'시간표 미등록';$('#semesterLabel').textContent=timetable?semesterText():'—';$('#semesterMeta').textContent=timetable?'에브리타임 · Flow 일정 기준':'에브리타임 기준';const next=list.find(x=>x.endMinutes>mins);if(!timetable){$('#nextClassTitle').textContent='시간표 없음';$('#nextClassMeta').textContent='에브리타임 공유 링크로 가져오거나 개인 일정을 추가할 수 있습니다.'}else if(!list.length){$('#nextClassTitle').textContent='오늘 수업 없음';$('#nextClassMeta').textContent='공강이거나 등록된 일정이 없습니다.'}else if(!next){$('#nextClassTitle').textContent='오늘 일정 종료';$('#nextClassMeta').textContent=`마지막 일정 ${list.at(-1).end}`}else{$('#nextClassTitle').textContent=next.subject.name||'일정';const state=next.startMinutes<=mins?'진행 중':next.start;$('#nextClassMeta').textContent=[state,next.place||next.subject.place,next.subject.professor].filter(Boolean).join(' · ')}const box=$('#todayList');if(!timetable)box.innerHTML='<div class="empty-state">시간표를 가져오거나 개인 일정을 추가하세요.</div>';else if(!list.length)box.innerHTML='<div class="empty-state">오늘 등록된 수업이나 일정이 없습니다.</div>';else box.innerHTML=list.map(x=>`<${x.subject.custom?'button':'div'} class="today-row${x.subject.custom?' editable-row':''}" ${x.subject.custom?`type="button" data-custom-id="${esc(x.subject.id)}"`:''}><span class="today-time">${esc(timeLabel(x.start,x.end))}</span><span><strong>${esc(x.subject.name||'일정')}</strong><small>${esc([x.subject.professor,x.place||x.subject.place].filter(Boolean).join(' · '))}</small></span><span class="today-credit">${x.subject.credit?`${x.subject.credit}학점`:x.subject.custom?'개인 일정':''}</span></${x.subject.custom?'button':'div'}>`).join('');box.querySelectorAll('[data-custom-id]').forEach(el=>el.addEventListener('click',()=>openPersonalById(el.dataset.customId)));$('#emptyImportPanel').classList.toggle('hidden',!!timetable)}

function courseClass(subject){let h=0;for(const c of subject.name||'')h=(h*31+c.charCodeAt(0))|0;return`course-${Math.abs(h)%6}`}
function renderTimetable(){renderIdentity();const box=$('#timeGrid'),dayTabs=$('#dayTabs');dayTabs.innerHTML='';if(!timetable){$('#timetableMeta').textContent='시간표를 가져오거나 개인 일정을 추가하면 주간으로 표시합니다.';box.innerHTML='<div class="empty-state">에브리타임 시간표를 가져오거나 개인 일정을 추가하세요.</div>';return}const all=entries();$('#timetableMeta').textContent=`${semesterText()} · ${all.length}개 시간 블록`;const maxDay=Math.max(4,...all.map(x=>x.day));const days=Array.from({length:maxDay+1},(_,i)=>i);if(!all.length){box.innerHTML='<div class="empty-state">시간이 지정된 수업이 없습니다.</div>';return}const mobile=matchMedia('(max-width:820px)').matches;const minStart=Math.min(...all.map(x=>x.startMinutes)),maxEnd=Math.max(...all.map(x=>x.endMinutes));const start=Math.min(8*60,Math.floor(minStart/60)*60),end=Math.max(19*60,Math.ceil(maxEnd/60)*60),hourPx=mobile?72:74,totalHeight=((end-start)/60)*hourPx,axis=mobile?34:54,cols=mobile?`${axis}px repeat(${days.length},minmax(0,1fr))`:`${axis}px repeat(${days.length},minmax(120px,1fr))`;box.style.setProperty('--hour',`${hourPx}px`);box.style.minWidth=mobile?'0':'950px';let html=`<div class="grid-header" style="grid-template-columns:${cols}"><div class="grid-header-cell"></div>${days.map(d=>`<div class="grid-header-cell day-wide" data-grid-day="${d}">${DAY_NAMES[d]}</div>`).join('')}</div><div class="grid-body" style="grid-template-columns:${cols};height:${totalHeight}px"><div class="time-axis">`;for(let m=start;m<=end;m+=60)html+=`<span class="hour-label" style="top:${((m-start)/60)*hourPx}px">${String(Math.floor(m/60)).padStart(2,'0')}:00</span>`;html+='</div>';for(const d of days){const blocks=dayEntries(d).map(x=>{const top=((x.startMinutes-start)/60)*hourPx,height=Math.max(22,((x.endMinutes-x.startMinutes)/60)*hourPx),duration=x.endMinutes-x.startMinutes,compact=duration<60;const place=x.place||x.subject.place||'';const desktopMeta=[x.start,place,x.subject.professor].filter(Boolean).join(' · ');const mobileMeta=compact?'':[place].filter(Boolean).join(' · ');const tag=x.subject.custom?'button':'div';return`<${tag} ${x.subject.custom?`type="button" data-custom-id="${esc(x.subject.id)}"`:''} class="course-block ${courseClass(x.subject)}${x.subject.custom?' custom':''}${compact?' compact-block':''}" style="top:${top}px;height:${height}px" title="${esc(`${x.subject.name} ${x.start}-${x.end}`)}"><strong>${esc(x.subject.name||'일정')}</strong>${(mobile?mobileMeta:desktopMeta)?`<span>${esc(mobile?mobileMeta:desktopMeta)}</span>`:''}</${tag}>`}).join('');html+=`<div class="day-column" data-grid-day="${d}" style="height:${totalHeight}px">${blocks}</div>`}html+='</div>';box.innerHTML=html;box.querySelectorAll('[data-custom-id]').forEach(el=>el.addEventListener('click',()=>openPersonalById(el.dataset.customId)))}

function won(value){if(!Number.isFinite(value)||!value)return'—';return`${Math.round(value).toLocaleString('ko-KR')}원`}
function percent(value){if(!Number.isFinite(value)||!value)return'—';return`${value.toLocaleString('ko-KR',{maximumFractionDigits:1})}%`}
function universityDate(value=''){const s=String(value||'').trim();return /^\d{8}$/.test(s)?`${s.slice(0,4)}.${s.slice(4,6)}.${s.slice(6,8)}`:s}
function renderProfile(){renderIdentity();if(!profile)return;const p={...profile,...(profileData?.school||{})};$('#profileEnglish').textContent=p.englishName||'';$('#profileAddress').textContent=p.address||'';$('#profileType').textContent=[p.foundation,p.kind,p.campus].filter(Boolean).join(' · ');const metrics=profileData?.metrics||{},unavailable=new Set(profileData?.unavailable||[]),defs=[['tuition','등록금 공시지표',won],['scholarship','장학금 공시지표',won],['dormitory','기숙사 수용률',percent],['library','자료구입비 비율',percent]];$('#metricGrid').innerHTML=defs.map(([key,label,format])=>{const item=metrics[key],blocked=unavailable.has(key);return`<article class="metric-card${blocked?' metric-unavailable':''}"><span>${label}</span><strong>${format(item?.value)}</strong><small>${item?.year?`${item.year}년 대학정보공시`:blocked?'공공데이터 일시 제한':'데이터 없음'}</small></article>`}).join('');const basic=[['설립',p.foundation],['학교 구분',p.division||p.kind],['개교',universityDate(p.founded)],['지역',p.region],['캠퍼스',p.campus],['주소',p.address],['우편번호',p.postalCode],['전화',p.phone],['팩스',p.fax]];$('#basicGrid').innerHTML=basic.filter(x=>String(x[1]||'').trim()).map(([k,v])=>`<div class="basic-item"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('');const status=$('#profileDataStatus'),statusText=$('#profileDataStatusText');if(status&&statusText){if(profileLoadError){status.classList.remove('hidden');status.dataset.state='error';statusText.textContent='대학 공시정보를 불러오지 못했습니다. 학교 기본정보는 저장된 정보를 표시합니다.'}else if(profileData?.partial){status.classList.remove('hidden');status.dataset.state='partial';statusText.textContent=`외부 공공데이터 요청 제한으로 일부 공시지표(${(profileData.unavailable||[]).length}개)를 잠시 표시하지 못합니다.`}else{status.classList.add('hidden');status.removeAttribute('data-state')}}}
async function loadProfileData({force=false}={}){if(!profile)return null;if(profileData&&!force)return profileData;if(profileLoadPromise)return profileLoadPromise;profileLoadError='';const retry=$('#retryProfileBtn');if(retry)retry.disabled=true;profileLoadPromise=(async()=>{try{const next=await api('profile',{id:profile.id,name:profile.name});profileData=next;renderProfile();return next}catch(e){profileLoadError=e.message||'대학 공시정보를 불러오지 못했습니다.';console.warn(e);renderProfile();return null}finally{profileLoadPromise=null;if(retry)retry.disabled=false}})();return profileLoadPromise}
async function loadMajors(){if(!profile||majors.length)return majors;const box=$('#majorResults');box.innerHTML='<div class="search-state">학과 불러오는 중…</div>';try{const r=await api('majors',{id:profile.id,name:profile.name});majors=r.majors||[];renderMajorResults();return majors}catch(e){box.innerHTML=`<div class="search-state">${esc(e.message)}</div>`;return[]}}
function renderMajorResults(){const q=norm($('#majorSearch')?.value||''),list=majors.filter(m=>!q||norm(`${m.college}${m.name}${m.category}`).includes(q)).slice(0,150);$('#majorResults').innerHTML=list.length?list.map(m=>`<button class="major-button" type="button" data-major-id="${esc(m.id)}"><span><strong>${esc(m.name)}</strong><small>${esc([m.college,m.category,m.duration].filter(Boolean).join(' · '))}</small></span></button>`).join(''):'<div class="search-state">검색 결과가 없습니다.</div>';$('#majorResults').querySelectorAll('[data-major-id]').forEach(b=>b.addEventListener('click',()=>{const m=majors.find(x=>x.id===b.dataset.majorId);if(!m)return;major=m;write(MAJOR_KEY,m);trackUniversity('major_select');closeDialog($('#majorDialog'));renderIdentity();renderProfile();renderToday();toast(`${m.name} 저장됨`)}))}
function renderMajorDetail(){const box=$('#majorDetail');if(!major){box.classList.add('hidden');$('#majorDescription').textContent='학과를 선택하면 관련 정보를 저장합니다.';return}box.classList.remove('hidden');$('#majorDescription').textContent=`${major.college||''} · ${major.name}`;box.innerHTML=`<h3>${esc(major.name)}</h3><p>${esc([major.college,major.category,major.degree,major.duration,major.dayNight].filter(Boolean).join(' · '))}</p>`}

function personalSubject(id){return timetable?.subjects?.find(x=>x.custom&&x.id===id)||null}
function openPersonal(subject=null){const d=$('#personalDialog');if(!d)return;const editing=Boolean(subject?.custom);$('#personalDialogTitle').textContent=editing?'개인 일정 수정':'개인 일정 추가';$('#personalEditId').value=editing?subject.id:'';$('#personalName').value=editing?subject.name:'';const t=editing?subject.times?.[0]:null;$('#personalDay').value=String(t?.day??Math.max(0,todayIndex()));$('#personalStart').value=t?.start||'18:00';$('#personalEnd').value=t?.end||'19:00';$('#personalPlace').value=t?.place||subject?.place||'';$('#deletePersonalBtn').classList.toggle('hidden',!editing);openDialog('#personalDialog')}
function openPersonalById(id){const subject=personalSubject(id);if(subject)openPersonal(subject)}
function savePersonal(event){event.preventDefault();const tt=ensureTimetable();const name=$('#personalName').value.trim(),day=Number($('#personalDay').value),start=$('#personalStart').value,end=$('#personalEnd').value,place=$('#personalPlace').value.trim();const startMinutes=minutes(start),endMinutes=minutes(end);if(!name||!Number.isFinite(startMinutes)||!Number.isFinite(endMinutes))return toast('일정 이름과 시간을 확인하세요.');if(endMinutes<=startMinutes)return toast('종료 시간은 시작 시간보다 뒤여야 합니다.');const id=$('#personalEditId').value||`personal-${crypto.randomUUID?.()||Date.now()}`;const item={id,name,custom:true,credit:0,place,times:[{day,start,end,startMinutes,endMinutes,place}]};const index=tt.subjects.findIndex(x=>x.id===id);if(index>=0)tt.subjects[index]=item;else tt.subjects.push(item);persistTimetable();trackUniversity('personal_schedule');closeDialog($('#personalDialog'));renderIdentity();renderToday();renderTimetable();toast(index>=0?'개인 일정을 수정했습니다.':'개인 일정을 추가했습니다.')}
function deletePersonal(){const id=$('#personalEditId').value;if(!timetable||!id)return;timetable.subjects=(timetable.subjects||[]).filter(x=>x.id!==id);persistTimetable();closeDialog($('#personalDialog'));renderIdentity();renderToday();renderTimetable();toast('개인 일정을 삭제했습니다.')}

async function importTimetable(){const input=$('#everytimeUrl'),url=input.value.trim();if(!url){toast('공유 링크를 입력하세요.');return}const button=$('#runImportBtn');button.disabled=true;button.textContent='가져오는 중…';loading(true);try{const custom=(timetable?.subjects||[]).filter(x=>x.custom);const r=await api('import-everytime',{}, {method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url})});timetable=normalizeTimetable(r.timetable);timetable.subjects=[...(timetable.subjects||[]),...custom];persistTimetable();trackUniversity('timetable_import');input.value='';closeDialog($('#importDialog'));renderIdentity();renderToday();renderTimetable();toast(`${r.timetable.subjects.length}개 수업을 가져왔습니다.`)}catch(e){toast(e.message)}finally{loading(false);button.disabled=false;button.textContent='가져오기'}}

function exportBackup(){const payload={type:'flow-university-backup',version:1,exportedAt:new Date().toISOString(),profile,timetable,major,theme:localStorage.getItem(THEME_KEY)||'light'};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`flow-university-backup-${new Date().toISOString().slice(0,10)}.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('백업 파일을 저장했습니다.')}
async function importBackupFile(file){if(!file)return;try{const data=JSON.parse(await file.text());if(data?.type!=='flow-university-backup'||!data.profile?.name)throw new Error('Flow 대학 백업 파일이 아닙니다.');profile=data.profile;timetable=normalizeTimetable(data.timetable);major=data.major||null;write(PROFILE_KEY,profile);if(timetable)write(TIMETABLE_KEY,timetable);else remove(TIMETABLE_KEY);if(major)write(MAJOR_KEY,major);else remove(MAJOR_KEY);if(data.theme)localStorage.setItem(THEME_KEY,String(data.theme));profileData=null;profileLoadError='';majors=[];closeDialog($('#changeDialog'));showApp();renderToday();renderTimetable();window.dispatchEvent(new CustomEvent('flow:timetable-changed'));toast('백업을 불러왔습니다.')}catch(e){toast(e.message||'백업을 불러오지 못했습니다.')}finally{$('#backupFileInput').value=''}}

$('#universitySearch')?.addEventListener('input',queueSearch);
$('#universitySearch')?.addEventListener('keydown',e=>{if(e.key==='Enter')runSearch()});
$('#searchBtn')?.addEventListener('click',runSearch);
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.go)));
document.addEventListener('click',event=>{if(event.target.closest?.('[data-view]'))trackUniversity('tab_view');else if(event.target.closest?.('[data-flow-mode-switch="school"]'))trackUniversity('mode_switch')},{passive:true});
for(const id of ['#importSidebarBtn','#importTopBtn','#emptyImportBtn','#importTimetableBtn'])$(id)?.addEventListener('click',()=>openDialog('#importDialog'));
$('#runImportBtn')?.addEventListener('click',importTimetable);
$('#everytimeUrl')?.addEventListener('keydown',e=>{if(e.key==='Enter')importTimetable()});
$('#addPersonalBtn')?.addEventListener('click',()=>openPersonal());
$('#personalForm')?.addEventListener('submit',savePersonal);
$('#deletePersonalBtn')?.addEventListener('click',deletePersonal);
$('#chooseMajorBtn')?.addEventListener('click',()=>{openDialog('#majorDialog');void loadMajors()});
$('#majorSearch')?.addEventListener('input',renderMajorResults);
$('#changeUniversityBtn')?.addEventListener('click',()=>openDialog('#changeDialog'));
$('#mobileSchoolBtn')?.addEventListener('click',()=>openDialog('#changeDialog'));
$('#exportBackupBtn')?.addEventListener('click',exportBackup);
$('#importBackupBtn')?.addEventListener('click',()=>$('#backupFileInput')?.click());
$('#backupFileInput')?.addEventListener('change',e=>void importBackupFile(e.target.files?.[0]));
$('#clearUniversityBtn')?.addEventListener('click',()=>{remove(PROFILE_KEY);remove(TIMETABLE_KEY);remove(MAJOR_KEY);profile=timetable=major=null;profileData=null;profileLoadError='';majors=[];closeDialog($('#changeDialog'));showSetup();toast('대학 설정을 지웠습니다.')});
$('#retryProfileBtn')?.addEventListener('click',()=>void loadProfileData({force:true}));
$$('[data-close-dialog]').forEach(b=>b.addEventListener('click',()=>closeDialog(b.closest('dialog'))));
$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)closeDialog(d)}));
window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(currentView==='timetable')renderTimetable()},120)},{passive:true});
window.addEventListener('flow:timetable-changed',()=>{timetable=normalizeTimetable(read(TIMETABLE_KEY,null));renderIdentity();if(currentView==='today')renderToday();if(currentView==='timetable')renderTimetable()});

if(timetable)persistTimetable();
if(profile)showApp();else showSetup();