const TT_KEY='flow-university-timetable-v1';
const $=(s)=>document.querySelector(s);
function readTT(){try{return JSON.parse(localStorage.getItem(TT_KEY))}catch{return null}}
function writeTT(tt){localStorage.setItem(TT_KEY,JSON.stringify(tt));window.dispatchEvent(new CustomEvent('flow:timetable-changed'));}
function minutes(v){const [h,m]=String(v).split(':').map(Number);return h*60+m}
function normalizeSemester(){const tt=readTT();if(!tt)return;let s=String(tt.semester||'').trim();if(/^\d+$/.test(s))s=`${s}학기`;if(s&&s!==tt.semester){tt.semester=s;writeTT(tt)}const mobile=$('#mobileSemester');if(mobile&&tt.year)mobile.textContent=`${tt.year}년 ${s||''}`.trim();const label=$('#semesterLabel'),meta=$('#semesterMeta');if(label)label.textContent=tt.year?`${tt.year}년`:'—';if(meta)meta.textContent=s||'학기 정보 없음'}
function openPersonal(subject=null){const d=$('#personalDialog');if(!d)return;const editing=Boolean(subject?.custom);$('#personalDialogTitle').textContent=editing?'개인 일정 수정':'개인 일정 추가';$('#personalEditId').value=editing?subject.id:'';$('#personalName').value=editing?subject.name:'';const t=editing?subject.times?.[0]:null;$('#personalDay').value=String(t?.day??Math.max(0,(new Date().getDay()+6)%7));$('#personalStart').value=t?.start||'18:00';$('#personalEnd').value=t?.end||'19:00';$('#personalPlace').value=t?.place||subject?.place||'';$('#deletePersonalBtn').classList.toggle('hidden',!editing);if(!d.open)d.showModal()}
function savePersonal(e){e.preventDefault();const tt=readTT();if(!tt){alert('먼저 시간표를 가져와 주세요.');return}const name=$('#personalName').value.trim(),day=Number($('#personalDay').value),start=$('#personalStart').value,end=$('#personalEnd').value,place=$('#personalPlace').value.trim();if(!name||!start||!end)return;if(minutes(end)<=minutes(start)){alert('종료 시간은 시작 시간보다 뒤여야 합니다.');return}const id=$('#personalEditId').value||`personal-${Date.now()}`;const item={id,name,custom:true,credit:0,place,times:[{day,start,end,startMinutes:minutes(start),endMinutes:minutes(end),place}]};tt.subjects=Array.isArray(tt.subjects)?tt.subjects:[];const i=tt.subjects.findIndex(x=>x.id===id);if(i>=0)tt.subjects[i]=item;else tt.subjects.push(item);writeTT(tt);$('#personalDialog').close();location.reload()}
function deletePersonal(){const tt=readTT(),id=$('#personalEditId').value;if(!tt||!id)return;tt.subjects=(tt.subjects||[]).filter(x=>x.id!==id);writeTT(tt);$('#personalDialog').close();location.reload()}
function bindBlocks(){const tt=readTT();document.querySelectorAll('.course-block[data-subject-index]').forEach(el=>{const subject=tt?.subjects?.[Number(el.dataset.subjectIndex)];if(subject?.custom)el.addEventListener('click',()=>openPersonal(subject))})}
function fitMobileWeek(){if(innerWidth>820)return;const grid=$('#timeGrid');if(!grid)return;const days=Math.max(5,...[...grid.querySelectorAll('.day-column')].map(x=>Number(x.dataset.gridDay)+1));const axis=34;const col=Math.max(50,(grid.clientWidth-axis)/days);const cols=`${axis}px repeat(${days},minmax(0,${col}px))`;grid.querySelector('.grid-header')?.style.setProperty('grid-template-columns',cols);grid.querySelector('.grid-body')?.style.setProperty('grid-template-columns',cols);grid.style.minWidth='0';}
$('#addPersonalBtn')?.addEventListener('click',()=>openPersonal());$('#personalForm')?.addEventListener('submit',savePersonal);$('#deletePersonalBtn')?.addEventListener('click',deletePersonal);
const observer=new MutationObserver(()=>{normalizeSemester();fitMobileWeek();bindBlocks()});const target=$('#timeGrid');if(target)observer.observe(target,{childList:true,subtree:true});window.addEventListener('resize',fitMobileWeek,{passive:true});normalizeSemester();fitMobileWeek();bindBlocks();
