create table if not exists public.flow_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  label text not null default 'owner',
  created_at timestamptz not null default now()
);

alter table public.flow_admins enable row level security;
revoke all on table public.flow_admins from anon, authenticated;

create table if not exists public.flow_admin_probe_log (
  id bigint generated by default as identity primary key,
  checked_at timestamptz not null default now(),
  service text not null,
  action text not null,
  status integer not null,
  duration_ms integer not null,
  ok boolean not null
);

alter table public.flow_admin_probe_log enable row level security;
revoke all on table public.flow_admin_probe_log from anon, authenticated;
create index if not exists flow_admin_probe_log_checked_at_idx on public.flow_admin_probe_log (checked_at desc);

create or replace function public.flow_admin_overview(p_hours integer default 24)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_hours integer := greatest(1, least(coalesce(p_hours, 24), 168));
  v_since timestamptz := now() - make_interval(hours => greatest(1, least(coalesce(p_hours, 24), 168)));
  v_total bigint;
  v_unique bigint;
  v_profiles bigint;
  v_top jsonb;
  v_hourly jsonb;
  v_probes jsonb;
begin
  select count(*), count(distinct anon_id)
    into v_total, v_unique
  from public.flow_quest_events
  where occurred_at >= v_since;

  select count(*) into v_profiles from public.flow_profiles;

  select coalesce(jsonb_agg(jsonb_build_object('name', event_name, 'count', event_count) order by event_count desc, event_name), '[]'::jsonb)
    into v_top
  from (
    select event_name, count(*)::bigint as event_count
    from public.flow_quest_events
    where occurred_at >= v_since
    group by event_name
    order by event_count desc, event_name
    limit 12
  ) ranked;

  select coalesce(jsonb_agg(jsonb_build_object('hour', bucket, 'count', event_count) order by bucket), '[]'::jsonb)
    into v_hourly
  from (
    select date_trunc('hour', occurred_at) as bucket, count(*)::bigint as event_count
    from public.flow_quest_events
    where occurred_at >= v_since
    group by 1
    order by 1
  ) hours;

  select coalesce(jsonb_agg(jsonb_build_object(
      'checkedAt', checked_at,
      'service', service,
      'action', action,
      'status', status,
      'durationMs', duration_ms,
      'ok', ok
    ) order by checked_at desc), '[]'::jsonb)
    into v_probes
  from (
    select checked_at, service, action, status, duration_ms, ok
    from public.flow_admin_probe_log
    order by checked_at desc
    limit 24
  ) recent;

  return jsonb_build_object(
    'generatedAt', now(),
    'windowHours', v_hours,
    'activity', jsonb_build_object(
      'totalEvents', coalesce(v_total, 0),
      'uniqueAnonymous', coalesce(v_unique, 0),
      'registeredProfiles', coalesce(v_profiles, 0),
      'topEvents', coalesce(v_top, '[]'::jsonb),
      'hourly', coalesce(v_hourly, '[]'::jsonb)
    ),
    'probes', coalesce(v_probes, '[]'::jsonb)
  );
end;
$$;

revoke all on function public.flow_admin_overview(integer) from public, anon, authenticated;
grant execute on function public.flow_admin_overview(integer) to service_role;
